# Documentation Tour - Pytorch

[Release Blog](https://pytorch.org/blog/)

PyTorch is a popular open-source machine learning library built on top of the Torch library. It's particularly well-suited for deep learning applications due to its dynamic computational graph, which allows for more flexible and intuitive development.

## Key Features and Benefits:

- `Dynamic Computational Graph`: Unlike static frameworks, PyTorch allows you to define and modify the computational graph on the fly, making it easier to experiment and debug.
- `Tensor Operations`: PyTorch provides efficient tensor operations for numerical computations, essential for deep learning models.
- `Autograd`: Automatically calculates gradients for backpropagation, simplifying the training process.
- `CUDA Integration`: Supports GPU acceleration for faster training and inference, especially on large datasets.
- `Community and Ecosystem`: A large and active community contributes to PyTorch's development and provides a wealth of resources, including tutorials, libraries, and tools.

## PyTorch Family of Libraries

PyTorch has a growing ecosystem of libraries that extend its capabilities and simplify common tasks:

- **TorchVision**: Provides datasets, data loaders, and image transformations for computer vision tasks.
- **TorchText**: Offers data loading, preprocessing, and tokenization for natural language processing.
- **TorchAudio**: Provides tools for loading, preprocessing, and augmenting audio data.
- **Fairseq**: A sequence-to-sequence toolkit for tasks like machine translation, summarization, and text generation.
- **PyTorch Lightning**: A high-level wrapper that simplifies training, validation, and testing of deep learning models.

<div style="background-color: lightblue; color:black; padding: 10px;">
    We begin to cover the documentation from here onwards
</div>

# Pytorch Dcoumentation

PyTorch is an optimized tensor library for deep learning using GPUs and CPUs.

<div style="background-color: lightyellow; color:black; padding: 10px;">
Features described in this documentation are classified by release status:
<br/>
<br/>

Stable: These features will be maintained long-term and there should generally be no major performance limitations or gaps in documentation. We also expect to maintain backwards compatibility (although breaking changes can happen and notice will be given one release ahead of time).

Beta: These features are tagged as Beta because the API may change based on user feedback, because the performance needs to improve, or because coverage across operators is not yet complete. For Beta features, we are committing to seeing the feature through to the Stable classification. We are not, however, committing to backwards compatibility.

Prototype: These features are typically not available as part of binary distributions like PyPI or Conda, except sometimes behind run-time flags, and are at an early stage for feedback and testing.
</div>

- Community
- Developer Notes
- Language Bindings
- Python API
- Libraries

## PyTorch Design Philosophy

**Principle 1:  Usability over Performance**

Pytorch's primary goal is Usability. It'secondary goal is to provide this usability with a reasonable performance.

In more concrete terms, it is operated in a usability-first manner and try to avoid jumping to restriction-first regimes (for example, static shapes, graph-mode only) without a clear-eyed view of the tradeoffs. (snide on tensorflow lol)


**Principle 2: Simple Over Easy**

- Explicit is better than implicit

Simple / Explicit (to understand, debug): every tensor is associated with a device. The user explicitly specifies tensor device movement. Operations that require cross-device movement result in an error.

- Simple is better than complex

Easy / Implicit (to use): the user does not have to worry about devices; the system figures out the globally optimal device placement.

Some classic arguments in favor of this sort of design come from A Note on Distributed Computation (TLDR: Do not model resources with very different performance characteristics uniformly, the details will leak) and the End-to-End Principle (TLDR: building smarts into the lower-layers of the stack can prevent building performant features at higher layers in the stack, and often doesn’t work anyway). 

**Principle 3: Python First with Best In Class Language Interoperability**

PyTorch is not a Python binding into a monolithic C++ framework. It is built to be deeply integrated into Python. You can use it naturally like you would use NumPy, SciPy, scikit-learn, or other Python libraries. You can write your new neural network layers in Python itself, using your favorite libraries and use packages such as Cython and Numba. 

# Developer Notes

Content on this will be presented in the `Deep Dive on Pytorch` notebook. 

# Language Bindings

## C++

## Javadoc

## torch.deploy

# Python API

Making imports before implementations.

In [1]:
import importlib

In [2]:
def print_module_version(module:str):
    try:
        version = importlib.metadata.version(module)
        print(f"{module} version: ",version)
    except:
        print(f"We could not find a version for {module} or the module is not installed.")

In [3]:
import torch
print_module_version("torch")
import torchaudio
print_module_version("torchaudio")
import torchvision
print_module_version("torchvision")

torch version:  2.0.0
torchaudio version:  2.0.0
torchvision version:  0.15.0


## torch

The torch package contains data structures for multi-dimensional tensors and defines mathematical operations over these tensors. Additionally, it provides many utilities for efficient serialization of Tensors and arbitrary types, and other useful utilities.

It has a CUDA counterpart, that enables you to run your tensor computations on an NVIDIA GPU with compute capability >= 3.0.

<div style="background-color: lightyellow; color:black; padding: 10px;">
Compute capability is a version number assigned by NVIDIA to its GPU architectures, indicating the set of hardware and software features supported by a particular GPU. It helps determine compatibility with CUDA versions and features, impacting performance and efficiency
</div>

### Tensors

`is_tensor` - Returns True if obj is a PyTorch tensor.

In [6]:
import numpy as np

x2 = [1,2,3]
x3 = np.array([1,2,3])
x4 = torch.tensor([1,2,3])
print(torch.is_tensor(x2))
print(torch.is_tensor(x3))
print(torch.is_tensor(x4))


False
False
True


In [18]:
x4.type()

'torch.LongTensor'

`is_storage` - Returns True if obj is a PyTorch storage object.

`is_complex` - Returns True if the data type of input is a complex data type i.e., one of torch.complex64, and torch.complex128.

In [11]:
real_part = torch.tensor([1.0, 2.0, 3.0])
imaginary_part = torch.tensor([0.5, 1.5, 2.5])

# Combine them into a complex tensor
complex_tensor = torch.complex(real_part, imaginary_part)

torch.is_complex(complex_tensor)

True

`is_conj` - Returns True if the input is a conjugated tensor, i.e. its conjugate bit is set to True.


>Conjugate Bit: PyTorch uses a “conjugate bit” to efficiently manage conjugation without immediately altering data. This allows for lazy evaluation, where the actual conjugation is materialized only when necessary

In [13]:
torch.is_conj(complex_tensor)

False

In [16]:
print(complex_tensor)
conj_tensor = torch.conj(complex_tensor)
conj_tensor

tensor([1.+0.5000j, 2.+1.5000j, 3.+2.5000j])


tensor([1.-0.5000j, 2.-1.5000j, 3.-2.5000j])

In [17]:
torch.is_conj(conj_tensor)


True

`is_floating_point` - Returns True if the data type of input is a floating point data type i.e., one of torch.float64, torch.float32, torch.float16, and torch.bfloat16

In [25]:
x4 = torch.tensor([1,2,3])
print(torch.is_floating_point(x4[0]))
print(torch.is_floating_point(torch.tensor([4.0])))

False
True


`is_nonzero` - Returns True if the input is a single element tensor which is not equal to zero after type conversions. i.e. not equal to torch.tensor([0.]) or torch.tensor([0]) or torch.tensor([False]). 

Throws a RuntimeError if torch.numel() != 1 (even in case of sparse tensors).

In [28]:
print(torch.is_nonzero(torch.tensor([0.])))
print(torch.is_nonzero(torch.tensor([1.5])))
print(torch.is_nonzero(torch.tensor([False])))
print(torch.is_nonzero(torch.tensor([3])))

False
True
False
True


In [29]:
print(torch.is_nonzero(torch.tensor([])))

RuntimeError: Boolean value of Tensor with no values is ambiguous

In [30]:
print(torch.is_nonzero(torch.tensor([1, 3, 5])))

RuntimeError: Boolean value of Tensor with more than one value is ambiguous

`set_default_dtype` - Sets the default floating point dtype to d. Supports floating point dtype as inputs. Other dtypes will cause torch to raise an exception.

When PyTorch is initialized its default floating point dtype is torch.float32, and the intent of set_default_dtype(torch.float64) is to facilitate NumPy-like type inference. The default floating point dtype is used to:

- Implicitly determine the default complex dtype. When the default floating type is float16, the default complex dtype is complex32. For float32, the default complex dtype is complex64. For float64, it is complex128. For bfloat16, an exception will be raised because there is no corresponding complex type for bfloat16.

- Infer the dtype for tensors constructed using Python floats or complex Python numbers. See examples below.

- Determine the result of type promotion between bool and integer tensors and Python floats and complex Python numbers.

In [34]:
# initial default for floating point is torch.float32
# Python floats are interpreted as float32
print(torch.tensor([1.2, 3]).dtype)
# initial default for floating point is torch.complex64
# Complex Python numbers are interpreted as complex64
torch.tensor([1.2, 3j]).dtype

torch.float16


torch.complex32

In [37]:
torch.set_default_dtype(torch.float64)
# Python floats are now interpreted as float64
print(torch.tensor([1.2, 3]).dtype ) # a new floating point tensor
# Complex Python numbers are now interpreted as complex128
print(torch.tensor([1.2, 3j]).dtype)  # a new complex tensor

torch.float64
torch.complex128


In [36]:
torch.set_default_dtype(torch.float16)
# Python floats are now interpreted as float16
print(torch.tensor([1.2, 3]).dtype)  # a new floating point tensor
# Complex Python numbers are now interpreted as complex128
print(torch.tensor([1.2, 3j]).dtype)  # a new complex tensor

torch.float16
torch.complex32


`get_default_dtype`-Get the current default floating point torch.dtype.

In [38]:
torch.get_default_dtype()  # initial default for floating point is torch.float32

torch.float64

In [39]:
torch.set_default_dtype(torch.float16)
torch.get_default_dtype()  # default is now changed to torch.float64

torch.float16

In [40]:
torch.set_default_dtype(torch.float64)


`set_default_device` - Sets the default torch.Tensor to be allocated on device. This does not affect factory function calls which are called with an explicit device argument. Factory calls will be performed as if they were passed device as an argument.

To only temporarily change the default device instead of setting it globally, use with torch.device(device): instead.

The default device is initially cpu. If you set the default tensor device to another device (e.g., cuda) without a device index, tensors will be allocated on whatever the current device for the device type, even after torch.cuda.set_device() is called.


<div style="background-color:pink;color:'black'">
This function imposes a slight performance cost on every Python call to the torch API (not just factory functions).
<br>
<br>
This doesn’t affect functions that create tensors that share the same memory as the input, like: torch.from_numpy() and torch.frombuffer()
</div>

In [48]:
torch.get_default_device()

device(type='cpu')

In [50]:
#If you don't have 'cuda' this will cause an assertion error when getting the default device. With this error `AssertionError: Torch not compiled with CUDA enabled`
torch.set_default_device('cuda') # the default index is 0 
torch.get_default_device()
# torch.set_default_device('cuda:1') #setting cuda device with an index 1

AssertionError: Torch not compiled with CUDA enabled

In [52]:
torch.set_default_device('cpu')
torch.get_default_device()

device(type='cpu')

`set_default_tensor_type` - Sets the default torch.Tensor type to floating point tensor type t. This type will also be used as default floating point type for type inference in torch.tensor().

The default floating point tensor type is initially torch.FloatTensor

In [60]:
torch.set_default_tensor_type(torch.FloatTensor)

In [59]:
print(torch.tensor([1.2, 3]).dtype )   # initial default for floating point is torch.float32
torch.set_default_tensor_type(torch.DoubleTensor)
print(torch.tensor([1.2, 3]).dtype)    # a new floating point tensor

torch.float32
torch.float64


In [62]:
torch.set_default_tensor_type(torch.FloatTensor) # Resetting it back to normal (THIS IS NOT NECESSARY TO IMPLEMENT)

`numel`-Returns the total number of elements in the input tensor.

In [66]:
a = torch.randn(1, 2, 3, 4, 5)
torch.numel(a)

120

In [67]:
a

tensor([[[[[-0.7011,  1.0103,  0.1894, -0.1033,  0.4773],
           [ 0.6510, -0.9430, -0.7517, -0.9230, -0.5099],
           [-0.6429, -0.7627, -1.2835, -0.0746, -0.1894],
           [ 0.6214, -0.9040,  1.6536,  0.1792,  1.5377]],

          [[ 0.0561, -0.0865, -0.3846, -0.7385,  0.8295],
           [ 1.2002, -0.0816, -0.6125,  0.0634, -0.3631],
           [ 0.6632, -0.8936,  2.1819, -1.0627, -0.9134],
           [-1.7668, -0.2770, -0.3437,  0.4954,  1.6466]],

          [[-0.4742,  0.1322, -0.2055, -0.3401,  0.1761],
           [ 0.6556, -1.8690, -0.3728,  1.5104, -0.2071],
           [ 0.9153,  0.5175, -0.1224, -0.3738, -1.2143],
           [-0.4021,  0.6956,  1.1614, -0.2235, -0.4531]]],


         [[[-1.6839, -0.5010, -0.3725,  0.2648,  1.0725],
           [-1.1364,  1.4070,  0.9047,  1.3125, -0.0574],
           [ 0.6914, -0.4821,  0.4485, -0.0542, -0.3414],
           [-0.0939,  0.2098, -0.2662,  1.2091, -0.0903]],

          [[-0.2650, -1.3057,  0.3733,  0.1206,  0.2209],
    

In [68]:
a = torch.zeros(4,4)
torch.numel(a)

16

In [69]:
a

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

`set_printoptions`-Set options for printing. Items shamelessly taken from NumPy

In [71]:
# Limit the precision of elements
torch.set_printoptions(precision=2)
torch.tensor([1.12345])


tensor([1.12])

In [72]:
# Limit the number of elements shown
torch.set_printoptions(threshold=5)
torch.arange(10)


tensor([0, 1, 2,  ..., 7, 8, 9])

In [75]:
# Restore defaults
torch.set_printoptions(profile='default')
torch.tensor([1.12345])


tensor([1.1235])

In [74]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`set_flush_denormal` - Disables denormal floating numbers on CPU.

Returns True if your system supports flushing denormal numbers and it successfully configures flush denormal mode. set_flush_denormal() is supported on x86 architectures supporting SSE3 and AArch64 architecture.
<div style="background-color:lightyellow;color:'black'">
Denormal numbers, also known as subnormal numbers, are a special category of floating-point numbers used to represent values very close to zero that are smaller than the smallest normal floating-point number.
<br>
</div>

In [77]:
torch.set_flush_denormal(True)

True

In [78]:
torch.tensor([1e-323], dtype=torch.float64)

tensor([0.], dtype=torch.float64)

In [79]:
torch.set_flush_denormal(False)

True

In [80]:
torch.tensor([1e-323], dtype=torch.float64)

tensor([9.8813e-324], dtype=torch.float64)

In [82]:
torch.set_flush_denormal(True) # Resetting it back

True

-- Creation Ops

`torch.tensor` - Constructs a tensor with no autograd history (also known as a “leaf tensor”, see Autograd mechanics) by copying data.

**Parameters**
data (array_like) – Initial data for the tensor. Can be a list, tuple, NumPy ndarray, scalar, and other types.

**Keyword Arguments**
dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: if None, infers data type from data.
device (torch.device, optional) – the device of the constructed tensor. If None and data is a tensor then the device of data is used. If None and data is not a tensor then the result tensor is constructed on the current device.
requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.
pin_memory (bool, optional) – If set, returned tensor would be allocated in the pinned memory. Works only for CPU tensors. Default: False.

In [83]:
torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [84]:
torch.tensor([0, 1])  # Type inference on data

tensor([0, 1])

In [86]:
torch.tensor([[0.11111, 0.222222, 0.3333333]],
             dtype=torch.float64,
             device=torch.device('cpu'))  # creates a double tensor on a CUDA device

tensor([[0.1111, 0.2222, 0.3333]], dtype=torch.float64)

In [87]:
torch.tensor(3.14159)  # Create a zero-dimensional (scalar) tensor

tensor(3.1416)

In [88]:
torch.tensor([])  # Create an empty tensor (of size (0,))

tensor([])

`sparse_coo_tensor`- Constructs a sparse tensor in COO(rdinate) format with specified values at the given indices.

<div style="background-color:lightyellow;color:black">
A sparse tensor is a multi-dimensional array where most elements are zero, allowing for efficient storage and computation by focusing on non-zero elements. It is represented using three components: indices, which specify the locations of non-zero elements; values, which are the non-zero entries themselves; and shape, which defines the dimensions of the tensor. 
<br>
<br>
The COO (Coordinate) format is a method for storing sparse matrices and tensors by explicitly listing their non-zero elements and their positions. It uses three arrays:
	1.	Row Indices: An array indicating the row positions of non-zero elements.
	2.	Column Indices: An array indicating the column positions of non-zero elements.
	3.	Data: An array containing the non-zero values themselves.
This format is also known as the ‘ijv’ or ‘triplet’ format and is particularly useful for constructing sparse matrices due to its simplicity and ease of conversion to other formats.
</div>

**Parameters**

- indices (array_like) – Initial data for the tensor. Can be a list, tuple, NumPy ndarray, scalar, and other types. Will be cast to a torch.LongTensor internally. The indices are the coordinates of the non-zero values in the matrix, and thus should be two-dimensional where the first dimension is the number of tensor dimensions and the second dimension is the number of non-zero values.
values (array_like) – Initial values for the tensor. Can be a list, tuple, NumPy ndarray, scalar, and other types.
- size (list, tuple, or torch.Size, optional) – Size of the sparse tensor. If not provided the size will be inferred as the minimum size big enough to hold all non-zero elements.

**Keyword Arguments**

- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: if None, infers data type from values.
- device (torch.device, optional) – the desired device of returned tensor. Default: if None, uses the current device for the default tensor type (see torch.set_default_device()). device will be the CPU for CPU tensor types and the current CUDA device for CUDA tensor types.
pin_memory (bool, optional) – If set, returned tensor would be allocated in the pinned memory. Works only for CPU tensors. Default: False.
- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.
- check_invariants (bool, optional) – If sparse tensor invariants are checked. Default: as returned by torch.sparse.check_sparse_tensor_invariants.is_enabled(), initially False.
- is_coalesced (bool, optional) – When``True``, the caller is responsible for providing tensor indices that correspond to a coalesced tensor. If the check_invariants flag is False, no error will be raised if the prerequisites are not met and this will lead to silently incorrect results. To force coalescion please use coalesce() on the resulting Tensor. Default: None: except for trivial cases (e.g. nnz < 2) the resulting Tensor has is_coalesced set to False`.


In [89]:
i = torch.tensor([[0, 1, 1],
                  [2, 0, 2]])
v = torch.tensor([3, 4, 5], dtype=torch.float32)
torch.sparse_coo_tensor(i, v, [2, 4])

tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([3., 4., 5.]),
       size=(2, 4), nnz=3, layout=torch.sparse_coo)

In [90]:

torch.sparse_coo_tensor(i, v)  # Shape inference


tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([3., 4., 5.]),
       size=(2, 3), nnz=3, layout=torch.sparse_coo)

In [92]:

torch.sparse_coo_tensor(i, v, [2, 4],
                        dtype=torch.float64,
                        device=torch.device('cpu'))


tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([3., 4., 5.]),
       size=(2, 4), nnz=3, dtype=torch.float64, layout=torch.sparse_coo)

In [95]:

S = torch.sparse_coo_tensor(torch.empty([1, 0]), [], [1])
S

tensor(indices=tensor([], size=(1, 0)),
       values=tensor([], size=(0,)),
       size=(1,), nnz=0, layout=torch.sparse_coo)

In [96]:

S = torch.sparse_coo_tensor(torch.empty([1, 0]), torch.empty([0, 2]), [1, 2])
S

tensor(indices=tensor([], size=(1, 0)),
       values=tensor([], size=(0, 2)),
       size=(1, 2), nnz=0, layout=torch.sparse_coo)

In [97]:
S.type()

'torch.sparse.FloatTensor'

`sparse_csr_tensor`- Constructs a sparse tensor in CSR (Compressed Sparse Row) with specified values at the given crow_indices and col_indices. Sparse matrix multiplication operations in CSR format are typically faster than that for sparse tensors in COO format. Make you have a look at the note on the data type of the indices.

The Compressed Sparse Row (CSR) format is a method for efficiently storing sparse matrices. It uses three one-dimensional arrays:

1. **Data Array**: Contains all the non-zero values of the matrix in row-major order.
2. **Indices Array**: Stores the column indices corresponding to each non-zero value in the data array.
3. **Indptr Array**: Holds the cumulative count of non-zero elements per row, marking where each row starts and ends in the data and indices arrays. Its length is $$n_{\text{rows}} + 1$$, with the last element being the total number of non-zero elements[2][3][7].

CSR format is advantageous for fast arithmetic operations and efficient matrix-vector multiplications.

**Parameters**

- crow_indices (array_like) – (B+1)-dimensional array of size (*batchsize, nrows + 1). The last element of each batch is the number of non-zeros. This tensor encodes the index in values and col_indices depending on where the given row starts. Each successive number in the tensor subtracted by the number before it denotes the number of elements in a given row.
- col_indices (array_like) – Column co-ordinates of each element in values. (B+1)-dimensional tensor with the same length as values.
values (array_list) – Initial values for the tensor. Can be a list, tuple, NumPy ndarray, scalar, and other types that represents a (1+K)-dimensional tensor where K is the number of dense dimensions.
- size (list, tuple, torch.Size, optional) – Size of the sparse tensor: (*batchsize, nrows, ncols, *densesize). If not provided, the size will be inferred as the minimum size big enough to hold all non-zero elements.

**Keyword Arguments**

- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: if None, infers data type from values.
- device (torch.device, optional) – the desired device of returned tensor. Default: if None, uses the current device for the default tensor type (see torch.set_default_device()). device will be the CPU for CPU tensor types and the current CUDA device for CUDA tensor types.
- pin_memory (bool, optional) – If set, returned tensor would be allocated in the pinned memory. Works only for CPU tensors. Default: False.
- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.
- check_invariants (bool, optional) – If sparse tensor invariants are checked. Default: as returned by torch.sparse.check_sparse_tensor_invariants.is_enabled(), initially False.



In [100]:
# Constructs a sparse tensor in CSR format.
crow_indices = torch.tensor([0, 1, 2])
col_indices = torch.tensor([2, 0])
values_csr = torch.tensor([3, 4])
sparse_csr = torch.sparse_csr_tensor(crow_indices, col_indices, values_csr)
print("Sparse CSR Tensor:\n", sparse_csr)

Sparse CSR Tensor:
 tensor(crow_indices=tensor([0, 1, 2]),
       col_indices=tensor([2, 0]),
       values=tensor([3, 4]), size=(2, 3), nnz=2, layout=torch.sparse_csr)


`sparse_csc_tensor`- Constructs a sparse tensor in CSC (Compressed Sparse Column) with specified values at the given ccol_indices and row_indices. Sparse matrix multiplication operations in CSC format are typically faster than that for sparse tensors in COO format. Make you have a look at the note on the data type of the indices.

<div style="background-color:lightyellow;color:black">
If the device argument is not specified the device of the given values and indices tensor(s) must match. If, however, the argument is specified the input Tensors will be converted to the given device and in turn determine the device of the constructed sparse tensor.
</div>

**Parameters**
- ccol_indices (array_like) – (B+1)-dimensional array of size (*batchsize, ncols + 1). The last element of each batch is the number of non-zeros. This tensor encodes the index in values and row_indices depending on where the given column starts. Each successive number in the tensor subtracted by the number before it denotes the number of elements in a given column.
- row_indices (array_like) – Row co-ordinates of each element in values. (B+1)-dimensional tensor with the same length as values.
values (array_list) – Initial values for the tensor. Can be a list, tuple, NumPy ndarray, scalar, and other types that represents a (1+K)-dimensional tensor where K is the number of dense dimensions.
- size (list, tuple, torch.Size, optional) – Size of the sparse tensor: (*batchsize, nrows, ncols, *densesize). If not provided, the size will be inferred as the minimum size big enough to hold all non-zero elements.

**Keyword Arguments**

- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: if None, infers data type from values.
device (torch.device, optional) – the desired device of returned tensor. Default: if None, uses the current device for the default tensor type (see torch.set_default_device()). device will be the CPU for CPU tensor types and the current CUDA device for CUDA tensor types.
- pin_memory (bool, optional) – If set, returned tensor would be allocated in the pinned memory. Works only for CPU tensors. Default: False.
- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.
- check_invariants (bool, optional) – If sparse tensor invariants are checked. Default: as returned by torch.sparse.check_sparse_tensor_invariants.is_enabled(), initially False.

In [106]:
ccol_indices = [0, 2, 4]
row_indices = [0, 1, 0, 1]
values = [1, 2, 3, 4]
torch.sparse_csc_tensor(torch.tensor(ccol_indices, dtype=torch.int64),
                        torch.tensor(row_indices, dtype=torch.int64),
                        torch.tensor(values), dtype=torch.double)

tensor(ccol_indices=tensor([0, 2, 4]),
       row_indices=tensor([0, 1, 0, 1]),
       values=tensor([1., 2., 3., 4.]), size=(2, 2), nnz=4,
       dtype=torch.float64, layout=torch.sparse_csc)

`sparse_bsr_tensor` - Constructs a sparse tensor in BSR (Block Compressed Sparse Row)) with specified 2-dimensional blocks at the given crow_indices and col_indices. Sparse matrix multiplication operations in BSR format are typically faster than that for sparse tensors in COO format. Make you have a look at the note on the data type of the indices.

**Parameters**

- crow_indices (array_like) – (B+1)-dimensional array of size (*batchsize, nrowblocks + 1). The last element of each batch is the number of non-zeros. This tensor encodes the block index in values and col_indices depending on where the given row block starts. Each successive number in the tensor subtracted by the number before it denotes the number of blocks in a given row.
- col_indices (array_like) – Column block co-ordinates of each block in values. (B+1)-dimensional tensor with the same length as values.
values (array_list) – Initial values for the tensor. Can be a list, tuple, NumPy ndarray, scalar, and other types that represents a (1 + 2 + K)-dimensional tensor where K is the number of dense dimensions.
- size (list, tuple, torch.Size, optional) – Size of the sparse tensor: (*batchsize, nrows * blocksize[0], ncols * blocksize[1], *densesize) where blocksize == values.shape[1:3]. If not provided, the size will be inferred as the minimum size big enough to hold all non-zero blocks.

**Keyword Arguments**

- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: if None, infers data type from values.
- device (torch.device, optional) – the desired device of returned tensor. Default: if None, uses the current device for the default tensor type (see torch.set_default_device()). device will be the CPU for CPU tensor types and the current CUDA device for CUDA tensor types.
- pin_memory (bool, optional) – If set, returned tensor would be allocated in the pinned memory. Works only for CPU tensors. Default: False.
- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.
- check_invariants (bool, optional) – If sparse tensor invariants are checked. Default: as returned by torch.sparse.check_sparse_tensor_invariants.is_enabled(), initially False.

In [107]:
crow_indices = [0, 1, 2]
col_indices = [0, 1]
values = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
torch.sparse_bsr_tensor(torch.tensor(crow_indices, dtype=torch.int64),
                        torch.tensor(col_indices, dtype=torch.int64),
                        torch.tensor(values), dtype=torch.double)

tensor(crow_indices=tensor([0, 1, 2]),
       col_indices=tensor([0, 1]),
       values=tensor([[[1., 2.],
                       [3., 4.]],

                      [[5., 6.],
                       [7., 8.]]]), size=(4, 4), nnz=2, dtype=torch.float64,
       layout=torch.sparse_bsr)

`sparse_bsc_tensor` - Constructs a sparse tensor in BSC (Block Compressed Sparse Column)) with specified 2-dimensional blocks at the given ccol_indices and row_indices. Sparse matrix multiplication operations in BSC format are typically faster than that for sparse tensors in COO format. Make you have a look at the note on the data type of the indices.

**Parameters**
- ccol_indices (array_like) – (B+1)-dimensional array of size (*batchsize, ncolblocks + 1). The last element of each batch is the number of non-zeros. This tensor encodes the index in values and row_indices depending on where the given column starts. Each successive number in the tensor subtracted by the number before it denotes the number of elements in a given column.
- row_indices (array_like) – Row block co-ordinates of each block in values. (B+1)-dimensional tensor with the same length as values.
- values (array_list) – Initial blocks for the tensor. Can be a list, tuple, NumPy ndarray, and other types that represents a (1 + 2 + K)-dimensional tensor where K is the number of dense dimensions.
- size (list, tuple, torch.Size, optional) – Size of the sparse tensor: (*batchsize, nrows * blocksize[0], ncols * blocksize[1], *densesize) If not provided, the size will be inferred as the minimum size big enough to hold all non-zero blocks.

**Keyword Arguments**

- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: if None, infers data type from values.
- device (torch.device, optional) – the desired device of returned tensor. Default: if None, uses the current device for the default tensor type (see torch.set_default_device()). device will be the CPU for CPU tensor types and the current CUDA device for CUDA tensor types.
- pin_memory (bool, optional) – If set, returned tensor would be allocated in the pinned memory. Works only for CPU tensors. Default: False.
- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.
- check_invariants (bool, optional) – If sparse tensor invariants are checked. Default: as returned by torch.sparse.check_sparse_tensor_invariants.is_enabled(), initially False.

In [108]:
ccol_indices = [0, 1, 2]
row_indices = [0, 1]
values = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
torch.sparse_bsc_tensor(torch.tensor(ccol_indices, dtype=torch.int64),
                        torch.tensor(row_indices, dtype=torch.int64),
                        torch.tensor(values), dtype=torch.double)

tensor(ccol_indices=tensor([0, 1, 2]),
       row_indices=tensor([0, 1]),
       values=tensor([[[1., 2.],
                       [3., 4.]],

                      [[5., 6.],
                       [7., 8.]]]), size=(4, 4), nnz=2, dtype=torch.float64,
       layout=torch.sparse_bsc)

`asarray` - Converts obj to a tensor.

obj can be one of:

- a tensor
- a NumPy array or a NumPy scalar
- a DLPack capsule
- an object that implements Python’s buffer protocol
- a scalar
- a sequence of scalars

<div style="background-color:lightyellow;color:black">
torch.tensor() creates a tensor that always copies the data from the input object. torch.from_numpy() creates a tensor that always shares memory from NumPy arrays. torch.frombuffer() creates a tensor that always shares memory from objects that implement the buffer protocol. torch.from_dlpack() creates a tensor that always shares memory from DLPack capsules.
</div>

**Parameters**

- obj (object) – a tensor, NumPy array, DLPack Capsule, object that implements Python’s buffer protocol, scalar, or sequence of scalars.

**Keyword Arguments**

- dtype (torch.dtype, optional) – the datatype of the returned tensor. Default: None, which causes the datatype of the returned tensor to be inferred from obj.
copy (bool, optional) – controls whether the returned tensor shares memory with obj. Default: None, which causes the returned tensor to share memory with obj whenever possible. If True then the returned tensor does not share its memory. If False then the returned tensor shares its memory with obj and an error is thrown if it cannot.
- device (torch.device, optional) – the device of the returned tensor. Default: None, which causes the device of obj to be used. Or, if obj is a Python sequence, the current default device will be used.
- requires_grad (bool, optional) – whether the returned tensor requires grad. Default: False, which causes the returned tensor not to require a gradient. If True, then the returned tensor will require a gradient, and if obj is also a tensor with an autograd history then the returned tensor will have the same history.

In [110]:
a = torch.tensor([1, 2, 3])
# Shares memory with tensor 'a'
b = torch.asarray(a)
a.data_ptr() == b.data_ptr()


True

In [111]:
# Forces memory copy
c = torch.asarray(a, copy=True)
a.data_ptr() == c.data_ptr()


False

In [112]:

a = torch.tensor([1., 2., 3.], requires_grad=True)
b = a + 2
b


tensor([3., 4., 5.], grad_fn=<AddBackward0>)

In [113]:
# Shares memory with tensor 'b', with no grad
c = torch.asarray(b)
c


tensor([3., 4., 5.])

In [114]:
# Shares memory with tensor 'b', retaining autograd history
d = torch.asarray(b, requires_grad=True)
d


tensor([3., 4., 5.], grad_fn=<AddBackward0>)

In [8]:

array = np.array([1, 2, 3])
# Shares memory with array 'array'
t1 = torch.asarray(array)
array.__array_interface__['data'][0] == t1.data_ptr()


True

In [116]:

# Copies memory due to dtype mismatch
t2 = torch.asarray(array, dtype=torch.float32)
array.__array_interface__['data'][0] == t2.data_ptr()

False

In [117]:

scalar = np.float64(0.5)
torch.asarray(scalar)

tensor(0.5000, dtype=torch.float64)

`as_tensor` - Converts data into a tensor, sharing data and preserving autograd history if possible.

**Parameters**

- obj (object) – a tensor, NumPy array, DLPack Capsule, object that implements Python’s buffer protocol, scalar, or sequence of scalars.

**Keyword Arguments**

- dtype (torch.dtype, optional) – the datatype of the returned tensor. Default: None, which causes the datatype of the returned tensor to be inferred from obj.
- device (torch.device, optional) – the device of the returned tensor. Default: None, which causes the device of obj to be used. Or, if obj is a Python sequence, the current default device will be used.
- requires_grad (bool, optional) – whether the returned tensor requires grad. Default: False, which causes the returned tensor not to require a gradient. If True, then the returned tensor will require a gradient, and if obj is also a tensor with an autograd history then the returned tensor will have the same history.


In [9]:
tensor_from_array = torch.as_tensor(array)
print(tensor_from_array.dtype)


torch.int64


/// Need to understand this better

`as_strided` - Creates a view of an existing torch.Tensor with specified size, stride, and storage_offset.

**Parameters**

- input (torch.Tensor) – the input tensor.
- size (tuple) – the new size of the tensor.
- stride (tuple) – the new stride of the tensor.
- storage_offset (int, optional) – the offset in the storage. Default: 0.


In [15]:
x  = torch.tensor([1,2,3,4,5,6,7,8,9,10,11,12])
x


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
t = torch.as_strided(x, size=(4,3), stride=(1,2))
t


tensor([[1, 3, 5],
        [2, 4, 6],
        [3, 5, 7],
        [4, 6, 8]])

`from_file` - Creates a CPU tensor with storage backed by a memory-mapped file.

**Parameters**

- filename (str) – the name of the file to map into memory.
- size (int, optional) – the size of the tensor to be created. If not provided, the size will be inferred from the file.
- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: None, which causes the datatype of the returned tensor to be inferred from the file.
- device (torch.device, optional) – the desired device of returned tensor. Default: None, which causes the device of the returned tensor to be inferred from the file.
- requires_grad (bool, optional) – whether the returned tensor requires grad. Default: False, which causes the returned tensor not to require a gradient.



In [25]:
t = torch.randn((2,5), dtype=torch.float64)
t

tensor([[-0.0050,  0.2827,  0.3792,  1.2395, -2.7689],
        [ 1.6283,  1.7129,  0.2101,  0.8047, -0.9882]], dtype=torch.float64)

In [32]:
x = torch.arange(10, dtype=torch.float32)
x.numpy().tofile("tensor_data.bin")  # Write in binary format

# Read back the data
y = torch.from_file("tensor_data.bin", size=(10), dtype=torch.float32)
print(y)


tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])


`from_numpy` - Creates a Tensor from a numpy.ndarray.

**Parameters**

- obj (numpy.ndarray) – the input numpy array.

**Keyword Arguments**

- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: None, which causes the datatype of the returned tensor to be inferred from obj.
- device (torch.device, optional) – the desired device of returned tensor. Default: None, which causes the device of obj to be used. Or, if obj is a Python sequence, the current default device will be used.
- requires_grad (bool, optional) – whether the returned tensor requires grad. Default: False, which causes the returned tensor not to require a gradient.

In [33]:
x = np.array([1, 2, 3])
t = torch.from_numpy(x)
t


tensor([1, 2, 3])

`from_dlpack` - Converts a tensor from an external library into a torch.Tensor.

**Parameters**

- obj (object) – a tensor, NumPy array, DLPack Capsule, object that implements Python’s buffer protocol, scalar, or sequence of scalars.

dlpack is an open standard for exchanging data between deep learning frameworks/libraries. It provides a way to share tensor data in memory between libraries like PyTorch, TensorFlow, MXNet, NumPy, and others without requiring data copying or transformation, ensuring high performance and interoperability.

`frombuffer` - Creates a 1D Tensor from an object that implements the Python buffer protocol.

**Parameters**

- obj (object) – an object that implements the Python buffer protocol.

**Keyword Arguments**

- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: None, which causes the datatype of the returned tensor to be inferred from obj.

- count (int, optional) – the number of elements to read. Default: -1, which means all elements.

- offset (int, optional) – the offset in the buffer. Default: 0.

- requires_grad (bool, optional) – whether the returned tensor requires grad. Default: False, which causes the returned tensor not to require a gradient.

This function’s behavior is undefined when passed an object implementing the buffer protocol whose data is not on the CPU. Doing so is likely to cause a segmentation fault.

This function does not try to infer the dtype (hence, it is not optional). Passing a different dtype than its source may result in unexpected behavior.

In [37]:
buffer = bytearray([0, 0, 128, 63, 0, 0, 0, 64]) 

t = torch.frombuffer(buffer, dtype=torch.float32)
t


tensor([1., 2.])

`zeros` - Returns a tensor filled with zeros, with shape defined by the size argument.

**Parameters**

- size (int or tuple of ints) – the shape of the tensor to be created.

**Keyword Arguments**

- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: None, which causes the datatype of the returned tensor to be inferred from obj.
- device (torch.device, optional) – the desired device of returned tensor. Default: None, which causes the device of obj to be used. Or, if obj is a Python sequence, the current default device will be used.
- requires_grad (bool, optional) – whether the returned tensor requires grad. Default: False, which causes the returned tensor not to require a gradient.



In [38]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

`zeros_like` - Returns a tensor filled with zeros, with the same size as input.

**Parameters**

- input (torch.Tensor) – the input tensor.

**Keyword Arguments**

- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: None, which causes the datatype of the returned tensor to be inferred from input.
- device (torch.device, optional) – the desired device of returned tensor. Default: None, which causes the device of input to be used. Or, if input is a Python sequence, the current default device will be used.
- requires_grad (bool, optional) – whether the returned tensor requires grad. Default: False, which causes the returned tensor not to require a gradient.


In [39]:
torch.zeros_like(torch.randn(2, 3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

`ones` - Returns a tensor filled with ones, with shape defined by the size argument.

**Parameters**

- size (int or tuple of ints) – the shape of the tensor to be created.

**Keyword Arguments**

- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: None, which causes the datatype of the returned tensor to be inferred from obj.
- device (torch.device, optional) – the desired device of returned tensor. Default: None, which causes the device of obj to be used. Or, if obj is a Python sequence, the current default device will be used.
- requires_grad (bool, optional) – whether the returned tensor requires grad. Default: False, which causes the returned tensor not to require a gradient.


In [40]:
torch.ones(2, 3)


tensor([[1., 1., 1.],
        [1., 1., 1.]])

`ones_like` - Returns a tensor filled with ones, with the same size as input.

**Parameters**

- input (torch.Tensor) – the input tensor.

**Keyword Arguments**

- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: None, which causes the datatype of the returned tensor to be inferred from input.
- device (torch.device, optional) – the desired device of returned tensor. Default: None, which causes the device of input to be used. Or, if input is a Python sequence, the current default device will be used.
- requires_grad (bool, optional) – whether the returned tensor requires grad. Default: False, which causes the returned tensor not to require a gradient.

In [41]:
torch.ones_like(torch.randn(2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

`arange` - Returns a 1-D tensor of values from start to end with step size, not including end.

**Parameters**

- start (int) – the starting value of the sequence.
- end (int) – the ending value of the sequence.
- step (int, optional) – the step size between each value in the sequence. Default: 1.

**Keyword Arguments**

- out (Tensor, optional) – the output tensor.
- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: if None, uses a global default (see torch.set_default_dtype()). If dtype is not given, infer the data type from the other input arguments. If any of start, end, or stop are floating-point, the dtype is inferred to be the default dtype, see get_default_dtype(). Otherwise, the dtype is inferred to be torch.int64.
- layout (torch.layout, optional) – the desired layout of returned Tensor. Default: torch.strided.
- device (torch.device, optional) – the desired device of returned tensor. Default: if None, uses the current device for the default tensor type (see torch.set_default_device()). device will be the CPU for CPU tensor types and the current CUDA device for CUDA tensor types.
- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.

In [43]:
torch.arange(0, 10, step=1.5)

tensor([0.0000, 1.5000, 3.0000, 4.5000, 6.0000, 7.5000, 9.0000])

`linspace` - Returns a 1-D tensor of size steps evenly spaced points from start to end.

**Parameters**

- start (float) – the starting value of the sequence.
- end (float) – the ending value of the sequence.
- steps (int) – the number of steps to take between start and end.

**Keyword Arguments**

- out (Tensor, optional) – the output tensor.
- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: if None, uses a global default (see torch.set_default_dtype()). If dtype is not given, infer the data type from the other input arguments. If any of start, end, or stop are floating-point, the dtype is inferred to be the default dtype, see get_default_dtype(). Otherwise, the dtype is inferred to be torch.int64.
- layout (torch.layout, optional) – the desired layout of returned Tensor. Default: torch.strided.
- device (torch.device, optional) – the desired device of returned tensor. Default: if None, uses the current device for the default tensor type (see torch.set_default_device()). device will be the CPU for CPU tensor types and the current CUDA device for CUDA tensor types.
- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.


In [44]:
torch.linspace(0, 10, steps=5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

It is similar for 'logspace'

In [46]:
torch.logspace(-10, 10, steps=5)

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [51]:
torch.logspace(start=2, end=8, steps=4, base=2)

tensor([  4.,  16.,  64., 256.])

`eye` - Returns a 2-D tensor with ones on the diagonal and zeros elsewhere.

**Parameters**

- n (int) – the number of rows in the output tensor.
- m (int, optional) – the number of columns in the output tensor. Default: n.

**Keyword Arguments**

- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: None, which causes the datatype of the returned tensor to be inferred from obj.
- device (torch.device, optional) – the desired device of returned tensor. Default: None, which causes the device of obj to be used. Or, if obj is a Python sequence, the current default device will be used.
- requires_grad (bool, optional) – whether the returned tensor requires grad. Default: False, which causes the returned tensor not to require a gradient.

In [52]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

- `empty` - Returns a tensor filled with uninitialized data.

- `empty_like` - Returns an uninitialized tensor with the same size as input.

- `empty_strided` - Creates a tensor with specified size and stride, filled with undefined data.


`full` - Creates a tensor of specified size filled with fill_value.

**Parameters**

- size (int or tuple of ints) – the shape of the tensor to be created.

**Keyword Arguments**

- fill_value (scalar, optional) – the value to fill the tensor with. Default: 0.
- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: None, which causes the datatype of the returned tensor to be inferred from fill_value.
- device (torch.device, optional) – the desired device of returned tensor. Default: None, which causes the device of fill_value to be used. Or, if fill_value is a Python sequence, the current default device will be used.
- requires_grad (bool, optional) – whether the returned tensor requires grad. Default: False, which causes the returned tensor not to require a gradient.

In [53]:
torch.full((2, 3), 5.0)

tensor([[5., 5., 5.],
        [5., 5., 5.]])

The `full_like` function is similar to `full`, but it creates a tensor with the same size as the input tensor and fills it with the specified value.

`quantize_per_tensor` - Converts a float tensor to a quantized tensor using given scale and zero point.

**Parameters**

- input (torch.Tensor) – the input tensor.
- scale (float) – the scale factor for quantization.
- zero_point (int) – the zero point for quantization.

**Keyword Arguments**

- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: None, which causes the datatype of the returned tensor to be inferred from input.
- device (torch.device, optional) – the desired device of returned tensor. Default: None, which causes the device of input to be used. Or, if input is a Python sequence, the current default device will be used.
- requires_grad (bool, optional) – whether the returned tensor requires grad. Default: False, which causes the returned tensor not to require a gradient.

In [57]:
torch.quantize_per_tensor(torch.tensor([-1.0, 0.0, 1.0, 2.0]), 0.1, 10, torch.quint8)

tensor([-1.,  0.,  1.,  2.], size=(4,), dtype=torch.quint8,
       quantization_scheme=torch.per_tensor_affine, scale=0.1, zero_point=10)

## torch.nn

## torch.nn.functional

## torch.Tensor

## Tensor Attributes

## Automatic Mixed Precision package - torch.amp

## Automatic differentiation package - torch.autograd

## torch.library

## torch.cpu

## torch.cuda

## Understanding CUDA Memory Usage

## torch.mps

## torch.xpu

## torch.mtia

## Meta device

## torch.backends

## torch.export

## Distributed communication package - torch.distributed

## torch.distributed.tensor

## Generic Join Context Manager

## Torch Distributed Elastic

## FullyShardedDataParallel

## Tensor Parallelism - torch.distributed.tensor.parallel

## Distributed Optimizers

## Pipeline Parallelism

## Distributed Checkpoint - torch.distributed.checkpoint

## Probability distributions - torch.distributions

## torch.compiler

## torch.fft

## torch.func

## torch.futures

## torch.fx

## torch.fx.experimental

## torch.hub

## TorchScript

## torch.linalg

## torch.monitor

## torch.signal

## torch.special

## torch.overrides

## torch.package

## torch.profiler

## torch.nn.init

## torch.nn.attention

## torch.onnx

## torch.optim

## Complex Numbers

## DDP Communication Hooks

## Quantization

## Distributed RPC Framework

## torch.random

## torch.masked

## torch.nested

## torch.Size

## torch.sparse

## torch.Storage

## torch.testing

## torch.utils

## Type Info

## Named Tensors

## Named Tensors operator coverage

## torch.__ config __

## torch.__ future __

## torch._logging

## Torch Environment Variables

# Libraries

## torchaudio

## torchdata

## TorchRec

## TorchServe

## torchtext

## torchvision

## Pytorch on XLA Devices