# Documentation Tour - Pytorch

[Release Blog](https://pytorch.org/blog/)

PyTorch is a popular open-source machine learning library built on top of the Torch library. It's particularly well-suited for deep learning applications due to its dynamic computational graph, which allows for more flexible and intuitive development.

## Key Features and Benefits:

- `Dynamic Computational Graph`: Unlike static frameworks, PyTorch allows you to define and modify the computational graph on the fly, making it easier to experiment and debug.
- `Tensor Operations`: PyTorch provides efficient tensor operations for numerical computations, essential for deep learning models.
- `Autograd`: Automatically calculates gradients for backpropagation, simplifying the training process.
- `CUDA Integration`: Supports GPU acceleration for faster training and inference, especially on large datasets.
- `Community and Ecosystem`: A large and active community contributes to PyTorch's development and provides a wealth of resources, including tutorials, libraries, and tools.

## PyTorch Family of Libraries

PyTorch has a growing ecosystem of libraries that extend its capabilities and simplify common tasks:

- **TorchVision**: Provides datasets, data loaders, and image transformations for computer vision tasks.
- **TorchText**: Offers data loading, preprocessing, and tokenization for natural language processing.
- **TorchAudio**: Provides tools for loading, preprocessing, and augmenting audio data.
- **Fairseq**: A sequence-to-sequence toolkit for tasks like machine translation, summarization, and text generation.
- **PyTorch Lightning**: A high-level wrapper that simplifies training, validation, and testing of deep learning models.

<div style="background-color: lightblue; color:black; padding: 10px;">
    We begin to cover the documentation from here onwards
</div>

# Pytorch Dcoumentation

PyTorch is an optimized tensor library for deep learning using GPUs and CPUs.

<div style="background-color: lightyellow; color:black; padding: 10px;">
Features described in this documentation are classified by release status:
<br/>
<br/>

Stable: These features will be maintained long-term and there should generally be no major performance limitations or gaps in documentation. We also expect to maintain backwards compatibility (although breaking changes can happen and notice will be given one release ahead of time).

Beta: These features are tagged as Beta because the API may change based on user feedback, because the performance needs to improve, or because coverage across operators is not yet complete. For Beta features, we are committing to seeing the feature through to the Stable classification. We are not, however, committing to backwards compatibility.

Prototype: These features are typically not available as part of binary distributions like PyPI or Conda, except sometimes behind run-time flags, and are at an early stage for feedback and testing.
</div>

- Community
- Developer Notes
- Language Bindings
- Python API
- Libraries

# Python API

Making imports before implementations.

In [1]:
import torch
import torchaudio
import torchvision

## torch

The torch package contains data structures for multi-dimensional tensors and defines mathematical operations over these tensors. Additionally, it provides many utilities for efficient serialization of Tensors and arbitrary types, and other useful utilities.

It has a CUDA counterpart, that enables you to run your tensor computations on an NVIDIA GPU with compute capability >= 3.0.

<div style="background-color: lightyellow; color:black; padding: 10px;">
Compute capability is a version number assigned by NVIDIA to its GPU architectures, indicating the set of hardware and software features supported by a particular GPU. It helps determine compatibility with CUDA versions and features, impacting performance and efficiency
</div>

### Tensors

`is_tensor` - Returns True if obj is a PyTorch tensor.

In [9]:
import numpy as np

x2 = [1,2,3]
x3 = np.array([1,2,3])
x4 = torch.tensor([1,2,3])
print(torch.is_tensor(x2))
print(torch.is_tensor(x3))
print(torch.is_tensor(x4))


False
False
True


In [18]:
x4.type()

'torch.LongTensor'

`is_storage` - Returns True if obj is a PyTorch storage object.

`is_complex` - Returns True if the data type of input is a complex data type i.e., one of torch.complex64, and torch.complex128.

In [11]:
real_part = torch.tensor([1.0, 2.0, 3.0])
imaginary_part = torch.tensor([0.5, 1.5, 2.5])

# Combine them into a complex tensor
complex_tensor = torch.complex(real_part, imaginary_part)

torch.is_complex(complex_tensor)

True

`is_conj` - Returns True if the input is a conjugated tensor, i.e. its conjugate bit is set to True.


>Conjugate Bit: PyTorch uses a “conjugate bit” to efficiently manage conjugation without immediately altering data. This allows for lazy evaluation, where the actual conjugation is materialized only when necessary

In [13]:
torch.is_conj(complex_tensor)

False

In [16]:
print(complex_tensor)
conj_tensor = torch.conj(complex_tensor)
conj_tensor

tensor([1.+0.5000j, 2.+1.5000j, 3.+2.5000j])


tensor([1.-0.5000j, 2.-1.5000j, 3.-2.5000j])

In [17]:
torch.is_conj(conj_tensor)


True

`is_floating_point` - Returns True if the data type of input is a floating point data type i.e., one of torch.float64, torch.float32, torch.float16, and torch.bfloat16

In [25]:
x4 = torch.tensor([1,2,3])
print(torch.is_floating_point(x4[0]))
print(torch.is_floating_point(torch.tensor([4.0])))

False
True


`is_nonzero` - Returns True if the input is a single element tensor which is not equal to zero after type conversions. i.e. not equal to torch.tensor([0.]) or torch.tensor([0]) or torch.tensor([False]). 

Throws a RuntimeError if torch.numel() != 1 (even in case of sparse tensors).

In [28]:
print(torch.is_nonzero(torch.tensor([0.])))
print(torch.is_nonzero(torch.tensor([1.5])))
print(torch.is_nonzero(torch.tensor([False])))
print(torch.is_nonzero(torch.tensor([3])))

False
True
False
True


In [29]:
print(torch.is_nonzero(torch.tensor([])))

RuntimeError: Boolean value of Tensor with no values is ambiguous

In [30]:
print(torch.is_nonzero(torch.tensor([1, 3, 5])))

RuntimeError: Boolean value of Tensor with more than one value is ambiguous

`set_default_dtype` - Sets the default floating point dtype to d. Supports floating point dtype as inputs. Other dtypes will cause torch to raise an exception.

When PyTorch is initialized its default floating point dtype is torch.float32, and the intent of set_default_dtype(torch.float64) is to facilitate NumPy-like type inference. The default floating point dtype is used to:

- Implicitly determine the default complex dtype. When the default floating type is float16, the default complex dtype is complex32. For float32, the default complex dtype is complex64. For float64, it is complex128. For bfloat16, an exception will be raised because there is no corresponding complex type for bfloat16.

- Infer the dtype for tensors constructed using Python floats or complex Python numbers. See examples below.

- Determine the result of type promotion between bool and integer tensors and Python floats and complex Python numbers.

In [34]:
# initial default for floating point is torch.float32
# Python floats are interpreted as float32
print(torch.tensor([1.2, 3]).dtype)
# initial default for floating point is torch.complex64
# Complex Python numbers are interpreted as complex64
torch.tensor([1.2, 3j]).dtype

torch.float16


torch.complex32

In [37]:
torch.set_default_dtype(torch.float64)
# Python floats are now interpreted as float64
print(torch.tensor([1.2, 3]).dtype ) # a new floating point tensor
# Complex Python numbers are now interpreted as complex128
print(torch.tensor([1.2, 3j]).dtype)  # a new complex tensor

torch.float64
torch.complex128


In [36]:
torch.set_default_dtype(torch.float16)
# Python floats are now interpreted as float16
print(torch.tensor([1.2, 3]).dtype)  # a new floating point tensor
# Complex Python numbers are now interpreted as complex128
print(torch.tensor([1.2, 3j]).dtype)  # a new complex tensor

torch.float16
torch.complex32


`get_default_dtype`-Get the current default floating point torch.dtype.

In [38]:
torch.get_default_dtype()  # initial default for floating point is torch.float32

torch.float64

In [39]:
torch.set_default_dtype(torch.float16)
torch.get_default_dtype()  # default is now changed to torch.float64

torch.float16

In [40]:
torch.set_default_dtype(torch.float64)


`set_default_device` - Sets the default torch.Tensor to be allocated on device. This does not affect factory function calls which are called with an explicit device argument. Factory calls will be performed as if they were passed device as an argument.

To only temporarily change the default device instead of setting it globally, use with torch.device(device): instead.

The default device is initially cpu. If you set the default tensor device to another device (e.g., cuda) without a device index, tensors will be allocated on whatever the current device for the device type, even after torch.cuda.set_device() is called.


<div style="background-color:pink;color:'black'">
This function imposes a slight performance cost on every Python call to the torch API (not just factory functions).
<br>
<br>
This doesn’t affect functions that create tensors that share the same memory as the input, like: torch.from_numpy() and torch.frombuffer()
</div>

In [48]:
torch.get_default_device()

device(type='cpu')

In [50]:
#If you don't have 'cuda' this will cause an assertion error when getting the default device. With this error `AssertionError: Torch not compiled with CUDA enabled`
torch.set_default_device('cuda') # the default index is 0 
torch.get_default_device()
# torch.set_default_device('cuda:1') #setting cuda device with an index 1

AssertionError: Torch not compiled with CUDA enabled

In [52]:
torch.set_default_device('cpu')
torch.get_default_device()

device(type='cpu')

`set_default_tensor_type` - Sets the default torch.Tensor type to floating point tensor type t. This type will also be used as default floating point type for type inference in torch.tensor().

The default floating point tensor type is initially torch.FloatTensor

In [60]:
torch.set_default_tensor_type(torch.FloatTensor)

In [59]:
print(torch.tensor([1.2, 3]).dtype )   # initial default for floating point is torch.float32
torch.set_default_tensor_type(torch.DoubleTensor)
print(torch.tensor([1.2, 3]).dtype)    # a new floating point tensor

torch.float32
torch.float64


In [62]:
torch.set_default_tensor_type(torch.FloatTensor) # Resetting it back to normal (THIS IS NOT NECESSARY TO IMPLEMENT)

`numel`-Returns the total number of elements in the input tensor.

In [66]:
a = torch.randn(1, 2, 3, 4, 5)
torch.numel(a)

120

In [67]:
a

tensor([[[[[-0.7011,  1.0103,  0.1894, -0.1033,  0.4773],
           [ 0.6510, -0.9430, -0.7517, -0.9230, -0.5099],
           [-0.6429, -0.7627, -1.2835, -0.0746, -0.1894],
           [ 0.6214, -0.9040,  1.6536,  0.1792,  1.5377]],

          [[ 0.0561, -0.0865, -0.3846, -0.7385,  0.8295],
           [ 1.2002, -0.0816, -0.6125,  0.0634, -0.3631],
           [ 0.6632, -0.8936,  2.1819, -1.0627, -0.9134],
           [-1.7668, -0.2770, -0.3437,  0.4954,  1.6466]],

          [[-0.4742,  0.1322, -0.2055, -0.3401,  0.1761],
           [ 0.6556, -1.8690, -0.3728,  1.5104, -0.2071],
           [ 0.9153,  0.5175, -0.1224, -0.3738, -1.2143],
           [-0.4021,  0.6956,  1.1614, -0.2235, -0.4531]]],


         [[[-1.6839, -0.5010, -0.3725,  0.2648,  1.0725],
           [-1.1364,  1.4070,  0.9047,  1.3125, -0.0574],
           [ 0.6914, -0.4821,  0.4485, -0.0542, -0.3414],
           [-0.0939,  0.2098, -0.2662,  1.2091, -0.0903]],

          [[-0.2650, -1.3057,  0.3733,  0.1206,  0.2209],
    

In [68]:
a = torch.zeros(4,4)
torch.numel(a)

16

In [69]:
a

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

`set_printoptions`-Set options for printing. Items shamelessly taken from NumPy

In [71]:
# Limit the precision of elements
torch.set_printoptions(precision=2)
torch.tensor([1.12345])


tensor([1.12])

In [72]:
# Limit the number of elements shown
torch.set_printoptions(threshold=5)
torch.arange(10)


tensor([0, 1, 2,  ..., 7, 8, 9])

In [75]:
# Restore defaults
torch.set_printoptions(profile='default')
torch.tensor([1.12345])


tensor([1.1235])

In [74]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`set_flush_denormal` - Disables denormal floating numbers on CPU.

Returns True if your system supports flushing denormal numbers and it successfully configures flush denormal mode. set_flush_denormal() is supported on x86 architectures supporting SSE3 and AArch64 architecture.
<div style="background-color:lightyellow;color:'black'">
Denormal numbers, also known as subnormal numbers, are a special category of floating-point numbers used to represent values very close to zero that are smaller than the smallest normal floating-point number.
<br>
</div>

In [77]:
torch.set_flush_denormal(True)

True

In [78]:
torch.tensor([1e-323], dtype=torch.float64)

tensor([0.], dtype=torch.float64)

In [79]:
torch.set_flush_denormal(False)

True

In [80]:
torch.tensor([1e-323], dtype=torch.float64)

tensor([9.8813e-324], dtype=torch.float64)

In [82]:
torch.set_flush_denormal(True) # Resetting it back

True

--

`torch.tensor` - Constructs a tensor with no autograd history (also known as a “leaf tensor”, see Autograd mechanics) by copying data.