# Documentation Tour - NumPy

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

- [Beginner's Guide](https://numpy.org/doc/stable/user/absolute_beginners.html)
- [User Guide](https://numpy.org/doc/stable/user/index.html#user)
- [API Reference](https://numpy.org/doc/stable/reference/index.html#reference)
- [Contributor's Guide](https://numpy.org/doc/stable/dev/index.html#devindex)

In [ ]:
%pip install numpy

If you get errors NOT related to installing of Numpy, you probably need not worry about that issue. Our main goal for now is to use NumPy properly and to its fullest extent. 

In [1]:
import numpy as np
print("Numpy Version is: ",np.__version__)

Numpy Version is:  1.26.4


# NumPy Reference

## NumPy Module Structure

Regular Namespaces


> A namespace is a collection of well-defined symbolic names along with information about the object that each name references. (Basically like a dictionary). 

> This is good when you are defining submodules too, they make things for interpreters to identify the specific submodule of a module to be loaded.

- numpy
- numpy.exceptions
- numpy.fft
- numpy.linalg
- numpy.polynomial
- numpy.random
- numpy.strings
- numpy.testing
- numpy.typing

Special purpose Namespaces

- numpy.ctypeslib - interacting with NumPy objects with ctypes 
- numpy.dtypes - dtype classes - (typically not used directly by end - users)
- numpy.emath - mathematical functions - with automatic domain
- numpy.lib - utilities & functionality - which do not fit the main namespace
- numpy.rec - record arrays (largely superseded by dataframe libraries)
- numpy.version - small module with more detailed version info

## numpy.exceptions

General exceptions used by Numpy. Note that some exceptions may be module specific, such as linear algebra errors.

>Only available from NumPy version 1.25

In [2]:
np.exceptions

<module 'numpy.exceptions' from '/Users/smatcha/anaconda3/lib/python3.11/site-packages/numpy/exceptions.py'>

Warnings

- ComplexWarning: The warning raised when casting a complex dtype to a real dtype.
- Visible Depreciation Warning: Visible deprecation warning.
- RankWarning: Warning related to Matrix Warning Issues

Exceptions

- AxisError: Axis Supplied was Invalid.
- DTypePromotionError: Multiple DTypes could not be converted to a common one. Comes from a form of `TypeError`.
- TooHardError: max_work was exceeded.

In [7]:
print(np.exceptions.ComplexWarning)
print(np.exceptions.VisibleDeprecationWarning)
print(np.exceptions.RankWarning)
print(np.exceptions.AxisError)
print(np.exceptions.DTypePromotionError)
print(np.exceptions.TooHardError)

<class 'numpy.exceptions.ComplexWarning'>
<class 'numpy.exceptions.VisibleDeprecationWarning'>
<class 'numpy.exceptions.RankWarning'>
<class 'numpy.exceptions.AxisError'>
<class 'numpy.exceptions.DTypePromotionError'>
<class 'numpy.exceptions.TooHardError'>


In [17]:
array = np.array([(1,2),(3,4)])
print(array.shape)

#Axis Error Demostration
_sum = np.sum(array,axis=0)
print(_sum)
_sum = np.sum(array,axis=1)
print(_sum)
_sum = np.sum(array,axis=2) # No Axis --> Should give Axis error
print(_sum)

(2, 2)
[4 6]
[3 7]


AxisError: axis 2 is out of bounds for array of dimension 2

In [18]:
np.result_type(np.dtype("M8[s]"), np.complex128)

DTypePromotionError: The DType <class 'numpy.dtypes.DateTime64DType'> could not be promoted by <class 'numpy.dtypes.Complex128DType'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtypes.DateTime64DType'>, <class 'numpy.dtypes.Complex128DType'>)

In [20]:
dtype1 = np.dtype([("field1", np.float64), ("field2", np.int64)])
dtype2 = np.dtype([("field1", np.float64)])
np.promote_types(dtype1, dtype2)  

DTypePromotionError: field names `('field1', 'field2')` and `('field1',)` mismatch.

In [5]:
import numpy as np

def complex_numpy_function(data):
    # Imagine this operation is too complex or the array is too large
    if data.size > 10**6:
        raise np.exceptions.TooHardError("This operation is too hard for the current dataset size!")
    
    # A simple operation that won't raise an error for small datasets
    return np.mean(data)

# Example usage
data = np.random.rand(10**7)  # A large dataset
result = complex_numpy_function(data)
print("Mean of data:", result)


TooHardError: This operation is too hard for the current dataset size!

## numpy.fft

Numpy Module for [Fourier Transforms](https://en.wikipedia.org/wiki/Fourier_transform).

## numpy.linalg

The NumPy linear algebra functions rely on [BLAS](https://en.wikipedia.org/wiki/Basic_Linear_Algebra_Subprograms) and [LAPACK](https://en.wikipedia.org/wiki/LAPACK) to provide efficient low level implementations of standard linear algebra algorithms. 


> Basic Linear Algebra Subprograms (BLAS) is a specification that prescribes a set of low-level routines for performing common linear algebra operations such as vector addition, scalar multiplication, dot products, linear combinations, and matrix multiplication. They are the de facto standard low-level routines for linear algebra libraries; the routines have bindings for both C ("CBLAS interface") and Fortran ("BLAS interface"). Although the BLAS specification is general, BLAS implementations are often optimized for speed on a particular machine, so using them can bring substantial performance benefits. BLAS implementations will take advantage of special floating point hardware such as vector registers or SIMD instructions.

> LAPACK ("Linear Algebra Package") is a standard software library for numerical linear algebra. It provides routines for solving systems of linear equations and linear least squares, eigenvalue problems, and singular value decomposition. It also includes routines to implement the associated matrix factorizations such as LU, QR, Cholesky and Schur decomposition. LAPACK was originally written in FORTRAN 77, but moved to Fortran 90 in version 3.2 (2008).[3] The routines handle both real and complex matrices in both single and double precision. LAPACK relies on an underlying BLAS implementation to provide efficient and portable computational building blocks for its routines.


References:

- Anderson, E.; Bai, Z.; Bischof, C.; Blackford, S.; Demmel, J.; Dongarra, J.; Du Croz, J.; Greenbaum, A.; Hammarling, S.; McKenney, A.; Sorensen, D. (1999). LAPACK Users' Guide (Third ed.). Philadelphia, PA: Society for Industrial and Applied Mathematics. ISBN 0-89871-447-8. Retrieved 28 May 2022.

- "LAPACK 3.2 Release Notes". 16 November 2008.


Those libraries may be provided by NumPy itself using C versions of a subset of their reference implementations but, when possible, highly optimized libraries that take advantage of specialized processor functionality are preferred. Examples of such libraries are [OpenBLAS](https://www.openblas.net), [MKL (TM)](https://en.wikipedia.org/wiki/Math_Kernel_Library), and [ATLAS](https://math-atlas.sourceforge.net). Because those libraries are multithreaded and processor dependent, environmental variables and external packages such as **threadpoolctl** may be needed to control the number of threads or specify the processor architecture.

The SciPy library also contains a `linalg` submodule, and there is overlap in the functionality provided by the SciPy and NumPy submodules. SciPy contains functions not found in numpy.linalg, such as functions related to [LU decomposition](https://en.wikipedia.org/wiki/LU_decomposition) and the [Schur decomposition](https://en.wikipedia.org/wiki/Schur_decomposition), multiple ways of calculating the pseudoinverse, and matrix transcendentals such as the matrix logarithm.

> The `@` operator is used for matrix multiplication between two matrices. `np.matmul` 

In [3]:
A = np.matrix([[2,4,5],[5,4,2],[3,1,6]])
B = np.matrix([[1,1,1],[5,3,7],[10,8,9]])
A,B

(matrix([[2, 4, 5],
         [5, 4, 2],
         [3, 1, 6]]),
 matrix([[ 1,  1,  1],
         [ 5,  3,  7],
         [10,  8,  9]]))

In [4]:
C = np.matmul(A,B)
print(C)
D = A@B
print(D)

[[72 54 75]
 [45 33 51]
 [68 54 64]]
[[72 54 75]
 [45 33 51]
 [68 54 64]]


### Matrix and vector products

| Function | Description |
|---|---|
| `dot(a, b[, out])` | Dot product of two arrays. |
| `linalg.multi_dot(arrays, *[, out])` | Compute the dot product of two or more arrays in a single function call, while automatically selecting the fastest evaluation order. |
| `vdot(a, b, /)` | Return the dot product of two vectors. |
| `vecdot(x1, x2, /[, out, casting, order, ...])` | Vector dot product of two arrays. |
| `linalg.vecdot(x1, x2, /, *[, axis])` | Computes the vector dot product. |
| `inner(a, b, /)` | Inner product of two arrays. |
| `outer(a, b[, out])` | Compute the outer product of two vectors. |
| `matmul(x1, x2, /[, out, casting, order, ...])` | Matrix product of two arrays. |
| `linalg.matmul(x1, x2, /)` | Computes the matrix product. |
| `tensordot(a, b[, axes])` | Compute tensor dot product along specified axes. |
| `linalg.tensordot(x1, x2, /, *[, axes])` | Compute tensor dot product along specified axes. |
| `einsum(subscripts, *operands[, out, dtype, ...])` | Evaluates the Einstein summation convention on the operands. |
| `einsum_path(subscripts, *operands[, optimize])` | Evaluates the lowest cost contraction order for an einsum expression by considering the creation of intermediate arrays. |
| `linalg.matrix_power(a, n)` | Raise a square matrix to the (integer) power n. |
| `kron(a, b)` | Kronecker product of two arrays. |
| `linalg.cross(x1, x2, /, *[, axis])` | Returns the cross product of 3-element vectors. |


### Decompositions

| Function | Description |
|----------|-------------|
| `linalg.cholesky(a, /, *[, upper])` | Cholesky decomposition. |
| `linalg.outer(x1, x2, /)` | Compute the outer product of two vectors. |
| `linalg.qr(a[, mode])` | Compute the QR factorization of a matrix. |
| `linalg.svd(a[, full_matrices, compute_uv, ...])` | Singular Value Decomposition (SVD). |
| `linalg.svdvals(x, /)` | Returns the singular values of a matrix (or a stack of matrices) `x`. |

### Matrix Eigenvalues

| Function | Description |
|----------|-------------|
| `linalg.eig(a)` | Compute the eigenvalues and right eigenvectors of a square array. |
| `linalg.eigh(a[, UPLO])` | Return the eigenvalues and eigenvectors of a complex Hermitian (conjugate symmetric) or a real symmetric matrix. |
| `linalg.eigvals(a)` | Compute the eigenvalues of a general matrix. |
| `linalg.eigvalsh(a[, UPLO])` | Compute the eigenvalues of a complex Hermitian or real symmetric matrix. |


### Norms and Other Numbers

| Function | Description |
|----------|-------------|
| `linalg.norm(x[, ord, axis, keepdims])` | Matrix or vector norm. |
| `linalg.matrix_norm(x, /, *[, keepdims, ord])` | Computes the matrix norm of a matrix (or a stack of matrices). |
| `linalg.vector_norm(x, /, *[, axis, ...])` | Computes the vector norm of a vector (or batch of vectors). |
| `linalg.cond(x[, p])` | Compute the condition number of a matrix. |
| `linalg.det(a)` | Compute the determinant of an array. |
| `linalg.matrix_rank(A[, tol, hermitian, rtol])` | Return the matrix rank using the SVD method. |
| `linalg.slogdet(a)` | Compute the sign and logarithm of the determinant of an array. |
| `trace(a[, offset, axis1, axis2, dtype, out])` | Return the sum along diagonals of the array. |
| `linalg.trace(x[, offset, dtype])` | Returns the sum along specified diagonals of a matrix. |



### Solving Equations and Inverting Matrices

| Function | Description |
|----------|-------------|
| `linalg.solve(a, b)` | Solve a linear matrix equation or system of linear scalar equations. |
| `linalg.tensorsolve(a, b[, axes])` | Solve the tensor equation `a x = b` for `x`. |
| `linalg.lstsq(a, b[, rcond])` | Return the least-squares solution to a linear matrix equation. |
| `linalg.inv(a)` | Compute the inverse of a matrix. |
| `linalg.pinv(a[, rcond, hermitian, rtol])` | Compute the (Moore-Penrose) pseudo-inverse of a matrix. |
| `linalg.tensorinv(a[, ind])` | Compute the 'inverse' of an N-dimensional array. |



### Other Matrix Operations

| Function | Description |
|----------|-------------|
| `diagonal(a[, offset, axis1, axis2])` | Return specified diagonals. |
| `linalg.diagonal(x[, offset])` | Returns specified diagonals of a matrix. |
| `linalg.matrix_transpose(x)` | Transposes a matrix (or a stack of matrices). |


### Code Implementation

In [12]:
import numpy as np
from numpy import linalg

# Matrix eigenvalues
a = np.array([[1, 2], [2, 3]])
eigvals, eigvecs = linalg.eig(a)
eighvals, eighvecs = linalg.eigh(a)
eigvals_general = linalg.eigvals(a)
eigvals_hermitian = linalg.eigvalsh(a)

# Norms and other numbers
x = np.array([1, 2, 3])
norm_val = linalg.norm(x)
matrix_norm_val = linalg.norm(a)
vector_norm_val = linalg.norm(x)
cond_val = linalg.cond(a)
det_val = linalg.det(a)
matrix_rank_val = linalg.matrix_rank(a)
sign, logdet_val = linalg.slogdet(a)
trace_val = np.trace(a)

# Solving equations and inverting matrices
b = np.array([5, 7])
solve_val = linalg.solve(a, b)
tensor_solve_val = linalg.tensorsolve(a, b)
lstsq_val, _, _, _ = linalg.lstsq(a, b)
inv_val = linalg.inv(a)
pinv_val = linalg.pinv(a)
# tensor_inv_val = linalg.tensorinv(a)

# Matrix operations
diagonal_val = np.diagonal(a)
transpose_val = np.transpose(a)

# Dot products, outer products, and matrix products
dot_val = np.dot(x, x)
multi_dot_val = linalg.multi_dot([a, a, a])
vdot_val = np.vdot(x, x)
# vecdot_val = np.vecdot(x, x)
inner_val = np.inner(x, x)
outer_val = np.outer(x, x)
matmul_val = np.matmul(a, a)
tensor_dot_val = np.tensordot(a, a)

# Einstein summation and related operations
einsum_val = np.einsum('ij,jk->ik', a, a)
einsum_path_val = np.einsum_path('ij,jk->ik', a, a)

# Matrix powers, Kronecker product, and cross product
matrix_power_val = linalg.matrix_power(a, 2)
kron_val = np.kron(a, a)
cross_val = np.cross([1, 2, 3], [4, 5, 6])

# Decompositions and factorization
# cholesky_val = linalg.cholesky(a)
qr_val = linalg.qr(a)
svd_u, svd_s, svd_vh = linalg.svd(a)
# svdvals_val = linalg.svdvals(a)


/var/folders/9c/gldj5rjn0699dnx6qgv9jyqr0000gn/T/ipykernel_45686/4028088339.py:26: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  lstsq_val, _, _, _ = linalg.lstsq(a, b)


In [13]:
def print_results():
    print("Matrix Eigenvalues:")
    print(f"Eigenvalues (linalg.eig): {eigvals}")
    print(f"Eigenvectors (linalg.eig): {eigvecs}")
    print(f"Eigenvalues (linalg.eigh): {eighvals}")
    print(f"Eigenvectors (linalg.eigh): {eighvecs}")
    print(f"Eigenvalues (linalg.eigvals): {eigvals_general}")
    print(f"Eigenvalues (linalg.eigvalsh): {eigvals_hermitian}\n")

    print("Norms and Other Numbers:")
    print(f"Vector Norm: {norm_val}")
    print(f"Matrix Norm: {matrix_norm_val}")
    print(f"Vector Norm (again): {vector_norm_val}")
    print(f"Condition Number: {cond_val}")
    print(f"Determinant: {det_val}")
    print(f"Matrix Rank: {matrix_rank_val}")
    print(f"Sign and Log Determinant: {sign}, {logdet_val}")
    print(f"Trace: {trace_val}\n")

    print("Solving Equations and Inverting Matrices:")
    print(f"Solved Value: {solve_val}")
    print(f"Tensor Solve Value: {tensor_solve_val}")
    print(f"Least Squares Solution: {lstsq_val}")
    print(f"Inverse Matrix: {inv_val}")
    print(f"Pseudo-Inverse Matrix: {pinv_val}\n")

    print("Matrix Operations:")
    print(f"Diagonal Values: {diagonal_val}")
    print(f"Transpose Matrix:\n{transpose_val}\n")

    print("Dot Products, Outer Products, and Matrix Products:")
    print(f"Dot Product: {dot_val}")
    print(f"Multi Dot Product: {multi_dot_val}")
    print(f"Vector Dot Product: {vdot_val}")
    print(f"Inner Product: {inner_val}")
    print(f"Outer Product:\n{outer_val}")
    print(f"Matrix Multiplication:\n{matmul_val}")
    print(f"Tensor Dot Product:\n{tensor_dot_val}\n")

    print("Einstein Summation and Related Operations:")
    print(f"Einstein Summation Result:\n{einsum_val}")
    print(f"Einstein Path Result:\n{einsum_path_val}\n")

    print("Matrix Powers, Kronecker Product, and Cross Product:")
    print(f"Matrix Power:\n{matrix_power_val}")
    print(f"Kronecker Product:\n{kron_val}")
    print(f"Cross Product: {cross_val}\n")

    print("Decompositions and Factorization:")
    print(f"QR Factorization:\n{qr_val}")
    print(f"SVD U Matrix:\n{svd_u}")
    print(f"SVD Singular Values:\n{svd_s}")
    print(f"SVD V^H Matrix:\n{svd_vh}")

In [14]:
print_results()

Matrix Eigenvalues:
Eigenvalues (linalg.eig): [-0.23606798  4.23606798]
Eigenvectors (linalg.eig): [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]
Eigenvalues (linalg.eigh): [-0.23606798  4.23606798]
Eigenvectors (linalg.eigh): [[-0.85065081  0.52573111]
 [ 0.52573111  0.85065081]]
Eigenvalues (linalg.eigvals): [-0.23606798  4.23606798]
Eigenvalues (linalg.eigvalsh): [-0.23606798  4.23606798]

Norms and Other Numbers:
Vector Norm: 3.7416573867739413
Matrix Norm: 4.242640687119285
Vector Norm (again): 3.7416573867739413
Condition Number: 17.94427190999918
Determinant: -1.0
Matrix Rank: 2
Sign and Log Determinant: -1.0, 0.0
Trace: 4

Solving Equations and Inverting Matrices:
Solved Value: [-1.  3.]
Tensor Solve Value: [-1.  3.]
Least Squares Solution: [-1.  3.]
Inverse Matrix: [[-3.  2.]
 [ 2. -1.]]
Pseudo-Inverse Matrix: [[-3.  2.]
 [ 2. -1.]]

Matrix Operations:
Diagonal Values: [1 3]
Transpose Matrix:
[[1 2]
 [2 3]]

Dot Products, Outer Products, and Matrix Products:
Dot Produc

### Exceptions

| Function | Description |
|----------|-------------|
| `linalg.LinAlgError` | Generic Python-exception-derived object raised by linalg functions. |

### Linear algebra on several matrices at once

This means that if for instance given an input array a.shape == (N, M, M), it is interpreted as a “stack” of N matrices, each of size M-by-M. . Similar specification applies to return values, for instance the determinant has det : (...) and will in this case return an array of shape det(a).shape == (N,)

## numpy.polynomial

## numpy.random

## numpy.strings

## numpy.testing

## numpy.typing