# Documentation Tour - NumPy

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

- [Beginner's Guide](https://numpy.org/doc/stable/user/absolute_beginners.html)
- [User Guide](https://numpy.org/doc/stable/user/index.html#user)
- [API Reference](https://numpy.org/doc/stable/reference/index.html#reference)
- [Contributor's Guide](https://numpy.org/doc/stable/dev/index.html#devindex)

In [59]:
%pip install --upgrade pip
%pip install --upgrade numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 30.7 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 24.2
    Uninstalling pip-24.2:
      Successfully uninstalled pip-24.2
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


If you get errors NOT related to installing of Numpy, you probably need not worry about that issue. Our main goal for now is to use NumPy properly and to its fullest extent. 

In [1]:
import numpy as np
print("Numpy Version is: ",np.__version__)

Numpy Version is:  1.26.4


# NumPy Reference

## NumPy Module Structure

Regular Namespaces


> A namespace is a collection of well-defined symbolic names along with information about the object that each name references. (Basically like a dictionary). 

> This is good when you are defining submodules too, they make things for interpreters to identify the specific submodule of a module to be loaded.

- numpy
- numpy.exceptions
- numpy.fft
- numpy.linalg
- numpy.polynomial
- numpy.random
- numpy.strings
- numpy.testing
- numpy.typing

Special purpose Namespaces

- numpy.ctypeslib - interacting with NumPy objects with ctypes 
- numpy.dtypes - dtype classes - (typically not used directly by end - users)
- numpy.emath - mathematical functions - with automatic domain
- numpy.lib - utilities & functionality - which do not fit the main namespace
- numpy.rec - record arrays (largely superseded by dataframe libraries)
- numpy.version - small module with more detailed version info

## numpy.exceptions

General exceptions used by Numpy. Note that some exceptions may be module specific, such as linear algebra errors.

>Only available from NumPy version 1.25

In [2]:
np.exceptions

<module 'numpy.exceptions' from '/Users/smatcha/anaconda3/lib/python3.11/site-packages/numpy/exceptions.py'>

Warnings

- ComplexWarning: The warning raised when casting a complex dtype to a real dtype.
- Visible Depreciation Warning: Visible deprecation warning.
- RankWarning: Warning related to Matrix Warning Issues

Exceptions

- AxisError: Axis Supplied was Invalid.
- DTypePromotionError: Multiple DTypes could not be converted to a common one. Comes from a form of `TypeError`.
- TooHardError: max_work was exceeded.

In [7]:
print(np.exceptions.ComplexWarning)
print(np.exceptions.VisibleDeprecationWarning)
print(np.exceptions.RankWarning)
print(np.exceptions.AxisError)
print(np.exceptions.DTypePromotionError)
print(np.exceptions.TooHardError)

<class 'numpy.exceptions.ComplexWarning'>
<class 'numpy.exceptions.VisibleDeprecationWarning'>
<class 'numpy.exceptions.RankWarning'>
<class 'numpy.exceptions.AxisError'>
<class 'numpy.exceptions.DTypePromotionError'>
<class 'numpy.exceptions.TooHardError'>


In [17]:
array = np.array([(1,2),(3,4)])
print(array.shape)

#Axis Error Demostration
_sum = np.sum(array,axis=0)
print(_sum)
_sum = np.sum(array,axis=1)
print(_sum)
_sum = np.sum(array,axis=2) # No Axis --> Should give Axis error
print(_sum)

(2, 2)
[4 6]
[3 7]


AxisError: axis 2 is out of bounds for array of dimension 2

In [18]:
np.result_type(np.dtype("M8[s]"), np.complex128)

DTypePromotionError: The DType <class 'numpy.dtypes.DateTime64DType'> could not be promoted by <class 'numpy.dtypes.Complex128DType'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtypes.DateTime64DType'>, <class 'numpy.dtypes.Complex128DType'>)

In [20]:
dtype1 = np.dtype([("field1", np.float64), ("field2", np.int64)])
dtype2 = np.dtype([("field1", np.float64)])
np.promote_types(dtype1, dtype2)  

DTypePromotionError: field names `('field1', 'field2')` and `('field1',)` mismatch.

In [5]:
import numpy as np

def complex_numpy_function(data):
    # Imagine this operation is too complex or the array is too large
    if data.size > 10**6:
        raise np.exceptions.TooHardError("This operation is too hard for the current dataset size!")
    
    # A simple operation that won't raise an error for small datasets
    return np.mean(data)

# Example usage
data = np.random.rand(10**7)  # A large dataset
result = complex_numpy_function(data)
print("Mean of data:", result)


TooHardError: This operation is too hard for the current dataset size!

## numpy.fft

Numpy Module for [Fourier Transforms](https://en.wikipedia.org/wiki/Fourier_transform).

## numpy.linalg

The NumPy linear algebra functions rely on [BLAS](https://en.wikipedia.org/wiki/Basic_Linear_Algebra_Subprograms) and [LAPACK](https://en.wikipedia.org/wiki/LAPACK) to provide efficient low level implementations of standard linear algebra algorithms. 


> Basic Linear Algebra Subprograms (BLAS) is a specification that prescribes a set of low-level routines for performing common linear algebra operations such as vector addition, scalar multiplication, dot products, linear combinations, and matrix multiplication. They are the de facto standard low-level routines for linear algebra libraries; the routines have bindings for both C ("CBLAS interface") and Fortran ("BLAS interface"). Although the BLAS specification is general, BLAS implementations are often optimized for speed on a particular machine, so using them can bring substantial performance benefits. BLAS implementations will take advantage of special floating point hardware such as vector registers or SIMD instructions.

> LAPACK ("Linear Algebra Package") is a standard software library for numerical linear algebra. It provides routines for solving systems of linear equations and linear least squares, eigenvalue problems, and singular value decomposition. It also includes routines to implement the associated matrix factorizations such as LU, QR, Cholesky and Schur decomposition. LAPACK was originally written in FORTRAN 77, but moved to Fortran 90 in version 3.2 (2008).[3] The routines handle both real and complex matrices in both single and double precision. LAPACK relies on an underlying BLAS implementation to provide efficient and portable computational building blocks for its routines.


References:

- Anderson, E.; Bai, Z.; Bischof, C.; Blackford, S.; Demmel, J.; Dongarra, J.; Du Croz, J.; Greenbaum, A.; Hammarling, S.; McKenney, A.; Sorensen, D. (1999). LAPACK Users' Guide (Third ed.). Philadelphia, PA: Society for Industrial and Applied Mathematics. ISBN 0-89871-447-8. Retrieved 28 May 2022.

- "LAPACK 3.2 Release Notes". 16 November 2008.


Those libraries may be provided by NumPy itself using C versions of a subset of their reference implementations but, when possible, highly optimized libraries that take advantage of specialized processor functionality are preferred. Examples of such libraries are [OpenBLAS](https://www.openblas.net), [MKL (TM)](https://en.wikipedia.org/wiki/Math_Kernel_Library), and [ATLAS](https://math-atlas.sourceforge.net). Because those libraries are multithreaded and processor dependent, environmental variables and external packages such as **threadpoolctl** may be needed to control the number of threads or specify the processor architecture.

The SciPy library also contains a `linalg` submodule, and there is overlap in the functionality provided by the SciPy and NumPy submodules. SciPy contains functions not found in numpy.linalg, such as functions related to [LU decomposition](https://en.wikipedia.org/wiki/LU_decomposition) and the [Schur decomposition](https://en.wikipedia.org/wiki/Schur_decomposition), multiple ways of calculating the pseudoinverse, and matrix transcendentals such as the matrix logarithm.

> Axes in NumPy Arrays

- Axis 0: This is the first axis of a NumPy array. It typically represents the rows in a 2D array (or the outermost dimension in higher-dimensional arrays). When you perform operations along axis 0, you are usually aggregating or processing across all rows.

- Axis 1: This is the second axis of a NumPy array. In a 2D array, it corresponds to the columns. When you perform operations along axis 1, you are aggregating or processing across all columns.

> The `@` operator is used for matrix multiplication between two matrices. `np.matmul` 

In [3]:
A = np.matrix([[2,4,5],[5,4,2],[3,1,6]])
B = np.matrix([[1,1,1],[5,3,7],[10,8,9]])
A,B

(matrix([[2, 4, 5],
         [5, 4, 2],
         [3, 1, 6]]),
 matrix([[ 1,  1,  1],
         [ 5,  3,  7],
         [10,  8,  9]]))

In [4]:
C = np.matmul(A,B)
print(C)
D = A@B
print(D)

[[72 54 75]
 [45 33 51]
 [68 54 64]]
[[72 54 75]
 [45 33 51]
 [68 54 64]]


### Matrix and vector products

| Function | Description |
|---|---|
| `dot(a, b[, out])` | Dot product of two arrays. |
| `linalg.multi_dot(arrays, *[, out])` | Compute the dot product of two or more arrays in a single function call, while automatically selecting the fastest evaluation order. |
| `vdot(a, b, /)` | Return the dot product of two vectors. |
| `vecdot(x1, x2, /[, out, casting, order, ...])` | Vector dot product of two arrays. |
| `linalg.vecdot(x1, x2, /, *[, axis])` | Computes the vector dot product. |
| `inner(a, b, /)` | Inner product of two arrays. |
| `outer(a, b[, out])` | Compute the outer product of two vectors. |
| `matmul(x1, x2, /[, out, casting, order, ...])` | Matrix product of two arrays. |
| `linalg.matmul(x1, x2, /)` | Computes the matrix product. |
| `tensordot(a, b[, axes])` | Compute tensor dot product along specified axes. |
| `linalg.tensordot(x1, x2, /, *[, axes])` | Compute tensor dot product along specified axes. |
| `einsum(subscripts, *operands[, out, dtype, ...])` | Evaluates the Einstein summation convention on the operands. |
| `einsum_path(subscripts, *operands[, optimize])` | Evaluates the lowest cost contraction order for an einsum expression by considering the creation of intermediate arrays. |
| `linalg.matrix_power(a, n)` | Raise a square matrix to the (integer) power n. |
| `kron(a, b)` | Kronecker product of two arrays. |
| `linalg.cross(x1, x2, /, *[, axis])` | Returns the cross product of 3-element vectors. |


#### Code Implementations

dot and multi_dot

In [21]:
a = np.matrix([[1, 0], [0, 1]])
b = np.matrix([[4, 1], [2, 2]])
a,b

(matrix([[1, 0],
         [0, 1]]),
 matrix([[4, 1],
         [2, 2]]))

In [22]:
np.dot(a, b)

matrix([[4, 1],
        [2, 2]])

In [16]:
from numpy.linalg import multi_dot
# Prepare some data
A = np.random.random((10000, 100))
B = np.random.random((100, 1000))
C = np.random.random((1000, 5))
D = np.random.random((5, 333))
# the actual dot multiplication
_ = multi_dot([A, B, C, D])
print(_.shape)
print(_)
_ = np.dot(np.dot(np.dot(A, B), C), D)
print(_.shape)
print(_)

(10000, 333)
[[31229.38409299 20939.90203527 40629.31284565 ... 30962.7328555
  15130.13869885 33696.14496461]
 [32460.15657146 21776.22504512 42222.79740772 ... 32181.91117219
  15717.12060996 35021.8272593 ]
 [33975.56956356 22783.2654148  44192.31254239 ... 33685.23677008
  16456.44989155 36653.8879767 ]
 ...
 [30819.00179991 20662.86000021 40085.70237776 ... 30557.55636294
  14928.63179029 33249.71888371]
 [31231.65505436 20946.6866803  40622.76184163 ... 30964.76317615
  15122.85907141 33692.71657728]
 [30386.01828732 20388.72955968 39530.60588209 ... 30124.40762162
  14713.88266383 32788.19320877]]
(10000, 333)
[[31229.38409299 20939.90203527 40629.31284565 ... 30962.7328555
  15130.13869885 33696.14496461]
 [32460.15657146 21776.22504512 42222.79740772 ... 32181.91117219
  15717.12060996 35021.8272593 ]
 [33975.56956356 22783.2654148  44192.31254239 ... 33685.23677008
  16456.44989155 36653.8879767 ]
 ...
 [30819.00179991 20662.86000021 40085.70237776 ... 30557.55636294
  14928.

vdot

In [23]:
a = np.array([[1, 4], [5, 6]])
b = np.array([[4, 1], [2, 2]])
a,b

(array([[1, 4],
        [5, 6]]),
 array([[4, 1],
        [2, 2]]))

Note that vdot handles multidimensional arrays differently than dot: **it does not perform a matrix product, but flattens input arguments to 1-D vectors first**. Consequently, it should only be used for vectors.

In [24]:
np.vdot(a, b)
np.vdot(b, a)

30

Inner Product

Ordinary inner product of vectors for 1-D arrays (without complex conjugation), **in higher dimensions a sum product over the last axes.**

In [25]:
a = np.arange(24).reshape((2,3,4))
b = np.arange(4)
a,b

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([0, 1, 2, 3]))

In [27]:
c = np.inner(a, b)
print(c.shape)
c

(2, 3)


array([[ 14,  38,  62],
       [ 86, 110, 134]])

In [28]:
a = np.arange(2).reshape((1,1,2))
b = np.arange(6).reshape((3,2))
a,b

(array([[[0, 1]]]),
 array([[0, 1],
        [2, 3],
        [4, 5]]))

In [30]:
c = np.inner(a, b)
print(c.shape)
c

(1, 1, 3)


array([[[1, 3, 5]]])

Outer Product

In [33]:
d=1j*np.linspace(2, -2, 5)
print(d.shape)
im = np.outer(1j*np.linspace(2, -2, 5), np.ones((5,)))
im

(5,)


array([[0.+2.j, 0.+2.j, 0.+2.j, 0.+2.j, 0.+2.j],
       [0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.-1.j, 0.-1.j, 0.-1.j, 0.-1.j, 0.-1.j],
       [0.-2.j, 0.-2.j, 0.-2.j, 0.-2.j, 0.-2.j]])

In [31]:
x = np.array(['a', 'b', 'c'], dtype=object)
np.outer(x, [1, 2, 3])

array([['a', 'aa', 'aaa'],
       ['b', 'bb', 'bbb'],
       ['c', 'cc', 'ccc']], dtype=object)

Tensordot

In [39]:

# Define the arrays
A = np.array([[1, 2],
              [3, 4]])

B = np.array([5, 6])

# Compute the tensor dot product
result = np.tensordot(A, B, axes=1)
print(result)
result = np.tensordot(A, B, axes=0)
print(result)


[17 39]
[[[ 5  6]
  [10 12]]

 [[15 18]
  [20 24]]]


einsum

`numpy.einsum(subscripts, *operands, out=None, dtype=None, order='K', casting='safe', optimize=False)`

Evaluates the Einstein summation convention on the operands.

Using the Einstein summation convention, many common multi-dimensional, linear algebraic array operations can be represented in a simple fashion. In implicit mode einsum computes these values.

In explicit mode, einsum provides further flexibility to compute other array operations that might not be considered classical Einstein summation operations, by disabling, or forcing summation over specified subscript labels.

**Parameters:**

* **subscripts:str :** Specifies the subscripts for summation as a comma-separated list of subscript labels. An implicit (classical Einstein summation) calculation is performed unless the explicit indicator "->" is included as well as subscript labels of the precise output form.
* **operands:** A list of array-like objects that are the arrays for the operation.
* **out:** Optional ndarray. If provided, the calculation is done into this array.
* **dtype:** Optional data-type. If provided, forces the calculation to use the specified data type. Note that you may have to also give a more liberal `casting` parameter to allow the conversions. Default is None.
* **order:** Optional string specifying the memory layout of the output. "C" means it should be C contiguous, "F" means it should be Fortran contiguous, "A" means it should be "F" if the inputs are all "F", "C" otherwise, and "K" means it should be as close to the layout as the inputs as is possible, including arbitrarily permuted axes. Default is "K".
* **casting:** Optional string controlling what kind of data casting may occur. Setting this to "unsafe" is not recommended, as it can adversely affect accumulations.
    * "no": Data types should not be cast at all.
    * "equiv": Only byte-order changes are allowed.
    * "safe": Only casts which can preserve values are allowed.
    * "same_kind": Only safe casts or casts within a kind, like float64 to float32, are allowed.
    * "unsafe": Any data conversions may be done.
  Default is "safe".
* **optimize:** Optional boolean or string controlling whether intermediate optimization should occur. No optimization will occur if False, and True will default to the "greedy" algorithm. Also accepts an explicit contraction list from the `np.einsum_path` function. See `np.einsum_path` for more details. Defaults to False.

**Returns:**

* **output:** ndarray. The calculation based on the Einstein summation convention.

In [45]:
a = np.arange(25).reshape(5,5)
print(a)
print(np.einsum('ii', a))
print(np.einsum('ij->j', a))
print(np.sum(a,axis=0))#row-wise
print(np.einsum('ij->i', a))
print(np.sum(a,axis=1))#column-wise

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
60
[50 55 60 65 70]
[50 55 60 65 70]
[ 10  35  60  85 110]
[ 10  35  60  85 110]


In [47]:
c = np.arange(6).reshape(2,3)
print(c)
print("")
print(np.einsum('ji', c))
print(np.einsum('ij->ji', c))
print(np.einsum(c, [1,0]))
print(np.transpose(c))

[[0 1 2]
 [3 4 5]]

[[0 3]
 [1 4]
 [2 5]]
[[0 3]
 [1 4]
 [2 5]]
[[0 3]
 [1 4]
 [2 5]]
[[0 3]
 [1 4]
 [2 5]]


einsum_path

Evaluates the lowest cost contraction order for an einsum expression by considering the creation of intermediate arrays.

In [50]:
np.random.seed(123)
a = np.random.rand(2, 2)
b = np.random.rand(2, 5)
c = np.random.rand(5, 2)
path_info = np.einsum_path('ij,jk,kl->il', a, b, c, optimize='greedy')
print(path_info[0])
print(path_info[1])

['einsum_path', (1, 2), (0, 1)]
  Complete contraction:  ij,jk,kl->il
         Naive scaling:  4
     Optimized scaling:  3
      Naive FLOP count:  1.200e+02
  Optimized FLOP count:  5.700e+01
   Theoretical speedup:  2.105
  Largest intermediate:  4.000e+00 elements
--------------------------------------------------------------------------
scaling                  current                                remaining
--------------------------------------------------------------------------
   3                   kl,jk->jl                                ij,jl->il
   3                   jl,ij->il                                   il->il


In [51]:
d=a@b@c
print(d.shape)

(2, 2)


matrix_power

In [54]:
np.linalg.matrix_power(2*np.eye(3),5)

array([[32.,  0.,  0.],
       [ 0., 32.,  0.],
       [ 0.,  0., 32.]])

np.kron

Kronecker product of two arrays.

Computes the Kronecker product, a composite array made of blocks of the second array scaled by the first.

In [56]:
import numpy as np
print(np.kron([1,10,100], [5,6,7]))
print(np.kron([1,10,100], [5,6,7]).shape)


[  5   6   7  50  60  70 500 600 700]
(9,)


np.cross

In [58]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.cross(x, y)

array([-3,  6, -3])

### Decompositions

| Function | Description |
|----------|-------------|
| `linalg.cholesky(a, /, *[, upper])` | Cholesky decomposition. |
| `linalg.outer(x1, x2, /)` | Compute the outer product of two vectors. |
| `linalg.qr(a[, mode])` | Compute the QR factorization of a matrix. |
| `linalg.svd(a[, full_matrices, compute_uv, ...])` | Singular Value Decomposition (SVD). |
| `linalg.svdvals(x, /)` | Returns the singular values of a matrix (or a stack of matrices) `x`. |

#### Code Implementations

[Cholesky Decomposition](https://en.wikipedia.org/wiki/Cholesky_decomposition)

The Cholesky decomposition is a decomposition of a Hermitian, positive-definite matrix into the product of a lower triangular matrix and its conjugate transpose, which is useful for efficient numerical solutions, e.g., Monte Carlo simulations.

$${\displaystyle \mathbf {A} =\mathbf {LL} ^{*}}$$


In [65]:
A = np.array([[4, 12, -16],
              [12, 37, -52],
              [-16, -52, 89]])

# Perform Cholesky decomposition
L = np.linalg.cholesky(A)

print(L)
print(L@np.transpose(L))

[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8. -4.  3.]]
[[  4.  12. -16.]
 [ 12.  37. -52.]
 [-16. -52.  89.]]


QR Factorization

Compute the qr factorization of a matrix.

QR factorization is a matrix decomposition that expresses a matrix as the product of an orthogonal matrix and an upper triangular matrix. This decomposition is particularly useful in numerical linear algebra for solving linear least squares problems, computing eigenvalues, and performing matrix inversion.

In [66]:
# Create a matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Perform QR factorization
Q, R = np.linalg.qr(A)

print("Q:\n", Q)
print("R:\n", R)

Q:
 [[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
R:
 [[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -7.58790979e-16]]


[SVD](https://en.wikipedia.org/wiki/Singular_value_decomposition) 

The Singular Value Decomposition (SVD) is a powerful matrix factorization technique that decomposes a matrix into three matrices:

1. **U:** An orthogonal matrix of dimensions m x m.
2. **Σ:** A diagonal matrix of dimensions m x n with non-negative real numbers on the diagonal.
3. **V^:** The conjugate transpose of an orthogonal matrix V of dimensions n x n.

**Mathematical Representation:**

```
M = UΣV^
```

**Significance of SVD:**

* **Singular Values:** The diagonal elements of Σ are called singular values. They represent the "scale" or importance of each dimension in the matrix.
* **Principal Components:** The columns of U are called left singular vectors. They represent the principal components of the data in the matrix.
* **Orthogonal Basis:** The columns of V* are called right singular vectors. They form an orthogonal basis for the column space of the matrix.

**Applications of SVD:**

* **Data Analysis:**
    * **Dimensionality Reduction:** SVD can be used to reduce the dimensionality of data while preserving the most important information.
    * **Principal Component Analysis (PCA):** PCA is a direct application of SVD for dimensionality reduction.
    * **Latent Semantic Analysis (LSA):** LSA uses SVD to uncover the underlying semantic structure of a collection of documents.
* **Image Processing:**
    * **Image Compression:** SVD can be used to compress images by discarding small singular values.
    * **Image Denoising:** SVD can be used to remove noise from images.
* **Recommendation Systems:**
    * **Collaborative Filtering:** SVD can be used to predict user preferences in collaborative filtering systems.
* **Numerical Linear Algebra:**
    * **Solving Systems of Linear Equations:** SVD can be used to solve systems of linear equations, even when the matrix is singular or ill-conditioned.

`linalg.svd(a, full_matrices=True, compute_uv=True, hermitian=False)`

When a is a 2D array, and full_matrices=False, then it is factorized as u @ np.diag(s) @ vh = (u * s) @ vh, where u and the Hermitian transpose of vh are 2D arrays with orthonormal columns and s is a 1D array of a’s singular values. 

In [67]:
import numpy as np
rng = np.random.default_rng()
a = rng.normal(size=(9, 6)) + 1j*rng.normal(size=(9, 6))
b = rng.normal(size=(2, 7, 8, 3)) + 1j*rng.normal(size=(2, 7, 8, 3))

In [69]:
U, S, Vh = np.linalg.svd(a, full_matrices=True)
U.shape, S.shape, Vh.shape

((9, 9), (6,), (6, 6))

In [70]:
U, S, Vh

(array([[-0.02856343-0.28113663j, -0.16482704-0.16951731j,
          0.40571265-0.27143117j,  0.15562044-0.02691557j,
          0.0509328 +0.11873621j, -0.35885863-0.07700922j,
         -0.51614568-0.20868509j,  0.05315293+0.34890927j,
          0.08465851-0.08907453j],
        [ 0.25102205-0.30094391j,  0.11564509-0.0385054j ,
          0.00408794+0.34182338j, -0.18414345-0.01607789j,
         -0.03300943+0.08540237j, -0.00638603+0.54164339j,
          0.1680757 +0.01149509j,  0.17421381+0.43499778j,
         -0.17390448-0.31707664j],
        [ 0.07368374+0.19398869j, -0.00306821-0.04219004j,
         -0.43260047-0.15580114j,  0.20395769+0.21372929j,
          0.44639212-0.08982823j,  0.10847507-0.03484118j,
         -0.03232913-0.25980736j, -0.05430668+0.45599239j,
         -0.34181987+0.19968387j],
        [ 0.14941359-0.05592978j,  0.04681513-0.01157549j,
          0.19911661+0.05942054j,  0.36114919-0.00873065j,
         -0.23467614-0.05779046j, -0.09919902+0.26981064j,
         -

### Matrix Eigenvalues

| Function | Description |
|----------|-------------|
| `linalg.eig(a)` | Compute the eigenvalues and right eigenvectors of a square array. |
| `linalg.eigh(a[, UPLO])` | Return the eigenvalues and eigenvectors of a complex Hermitian (conjugate symmetric) or a real symmetric matrix. |
| `linalg.eigvals(a)` | Compute the eigenvalues of a general matrix. |
| `linalg.eigvalsh(a[, UPLO])` | Compute the eigenvalues of a complex Hermitian or real symmetric matrix. |

#### Code Implementations

Eigen Decomposition (linalg.eig)

In linear algebra, eigendecomposition is the factorization of a matrix into a canonical form, whereby the matrix is represented in terms of its eigenvalues and eigenvectors. Only diagonalizable matrices can be factorized in this way. 

A (nonzero) vector v of dimension N is an eigenvector of a square N × N matrix A if it satisfies a linear equation of the form

$$\displaystyle \mathbf {A} \mathbf {v} =\lambda \mathbf {v}$$ 

In [72]:
import numpy as np
from numpy import linalg as LA

eigenvalues, eigenvectors = LA.eig(np.diag((1, 2, 3)))
eigenvalues, eigenvectors

(array([1., 2., 3.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [74]:
LA.eigvals(np.diag((1,2,3)))

array([1., 2., 3.])

Similar methods exist for hermitians. 


### Norms and Other Numbers

| Function | Description |
|----------|-------------|
| `linalg.norm(x[, ord, axis, keepdims])` | Matrix or vector norm. |
| `linalg.matrix_norm(x, /, *[, keepdims, ord])` | Computes the matrix norm of a matrix (or a stack of matrices). |
| `linalg.vector_norm(x, /, *[, axis, ...])` | Computes the vector norm of a vector (or batch of vectors). |
| `linalg.cond(x[, p])` | Compute the condition number of a matrix. |
| `linalg.det(a)` | Compute the determinant of an array. |
| `linalg.matrix_rank(A[, tol, hermitian, rtol])` | Return the matrix rank using the SVD method. |
| `linalg.slogdet(a)` | Compute the sign and logarithm of the determinant of an array. |
| `trace(a[, offset, axis1, axis2, dtype, out])` | Return the sum along diagonals of the array. |
| `linalg.trace(x[, offset, dtype])` | Returns the sum along specified diagonals of a matrix. |


trace - np.trace

Return the sum along diagonals of the array.

If a is 2-D, the sum along its diagonal with the given offset is returned, i.e., the sum of elements a[i,i+offset] for all i.

If a has more than two dimensions, then the axes specified by axis1 and axis2 are used to determine the 2-D sub-arrays whose traces are returned. The shape of the resulting array is the same as that of a with axis1 and axis2 removed.

#### Code Implementations

linalg.norm

Matrix or vector norm.

This function is able to return one of eight different matrix norms, or one of an infinite number of vector norms (described below), depending on the value of the ord parameter.

| Norm | Description | NumPy Function |
|---|---|---|
| **Frobenius norm** | `'fro'` | `np.linalg.norm(x, 'fro')` |
| **Nuclear norm** | `'nuc'` | `np.linalg.norm(x, 'nuc')` |
| **∞-norm** | `inf` | `np.linalg.norm(x, np.inf)` |
| **1-norm** | `1` | `np.linalg.norm(x, 1)` |
| **2-norm** (largest singular value) | `2` | `np.linalg.norm(x, 2)` |
| **-2-norm** (smallest singular value) | `-2` | `np.linalg.norm(x, -2)` |
| **Other** | `ord` | `np.linalg.norm(x, ord)` |

The **norm** of a vector is a measure of its length or magnitude. There are different types of norms, but the most common one is the **Euclidean norm**, also known as the **L2 norm**.

Euclidean (L2) Norm
$$
|v|_2 = \sqrt{v_1^2 + v_2^2 + \cdots + v_n^2}
$$

It represents the "straight-line" distance of the vector from the origin in n-dimensional space. For a 2D or 3D vector, this is the usual distance formula you may be familiar with.

Other Common Norms

1. **L1 Norm (Manhattan Norm)**:
   The L1 norm is the sum of the absolute values of the vector's components:
   \[
   \|v\|_1 = |v_1| + |v_2| + \dots + |v_n|
   \]
   This is often used in cases where the absolute distance (or difference) is more relevant, such as in taxicab geometry (hence the name "Manhattan norm").

2. **Infinity Norm (Max Norm)**:
   The infinity norm is the maximum absolute value of the vector's components:
   \[
   \|v\|_\infty = \max(|v_1|, |v_2|, \dots, |v_n|)
   \]
   This norm is used when only the largest component of a vector matters.

3. **Lp Norm** (Generalized Norm):
   The Lp norm is a generalization of the L1 and L2 norms and is defined as:
   \[
   \|v\|_p = \left( |v_1|^p + |v_2|^p + \dots + |v_n|^p \right)^{\frac{1}{p}}
   \]
   For \( p = 2 \), this reduces to the Euclidean norm, and for \( p = 1 \), it becomes the Manhattan norm.


In [76]:
a = np.arange(9) - 4
b = a.reshape((3, 3))
a,b

(array([-4, -3, -2, -1,  0,  1,  2,  3,  4]),
 array([[-4, -3, -2],
        [-1,  0,  1],
        [ 2,  3,  4]]))

In [78]:
print(LA.norm(a))
print(LA.norm(b))
print(LA.norm(b, 'fro'))
print(LA.norm(a, np.inf))
print(LA.norm(b, np.inf))
print(LA.norm(a, -np.inf))
print(LA.norm(b, -np.inf))

7.745966692414834
7.745966692414834
7.745966692414834
4.0
9.0
0.0
2.0


condition number - linalg.cond

The condition number of x is defined as the norm of x times the norm of the inverse of x [1]; the norm can be the usual L2-norm (root-of-sum-of-squares) or one of a number of other matrix norms.

In [79]:
a = np.array([[1, 0, -1], [0, 1, 0], [1, 0, 1]])
a

array([[ 1,  0, -1],
       [ 0,  1,  0],
       [ 1,  0,  1]])

In [80]:
print(LA.cond(a))
print(LA.cond(a, 'fro'))

1.4142135623730951
3.1622776601683795


determinant - linalg.det

Compute the determinant of an array.

In [81]:
print(LA.det(a))

2.0


In [82]:
a = np.array([ [[1, 2], [3, 4]], [[1, 2], [2, 1]], [[1, 3], [3, 1]] ])
print(a.shape)
np.linalg.det(a)

(3, 2, 2)


array([-2., -3., -8.])

Rank of a Matrix - linalg.matrix_rank

Return matrix rank of array using SVD method

Rank of the array is the number of singular values of the array that are greater than tol.

In [84]:
from numpy.linalg import matrix_rank
print(matrix_rank(np.eye(4))) # Full rank matrix
I=np.eye(4); I[-1,-1] = 0. # rank deficient matrix
print(matrix_rank(I))
print(matrix_rank(np.ones((4,)))) # 1 dimension - rank 1 unless all 0
print(matrix_rank(np.zeros((4,))))

4
3
1
0


trace - np.trace

Return the sum along diagonals of the array.

If a is 2-D, the sum along its diagonal with the given offset is returned, i.e., the sum of elements a[i,i+offset] for all i.

If a has more than two dimensions, then the axes specified by axis1 and axis2 are used to determine the 2-D sub-arrays whose traces are returned. The shape of the resulting array is the same as that of a with axis1 and axis2 removed.

In [94]:
print(np.trace(np.eye(3)))
a = np.arange(8).reshape((2,2,2))
print(a)
print(np.trace(a))
print(np.sum(a[0],axis=0))
print(np.sum(a[0],axis=1))
a = np.arange(24).reshape((2,2,2,3))
print(a)
print(np.trace(a).shape)
np.trace(a)

3.0
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[6 8]
[2 4]
[1 5]
[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]]


 [[[12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]]]]
(2, 3)


array([[18, 20, 22],
       [24, 26, 28]])


### Solving Equations and Inverting Matrices

| Function | Description |
|----------|-------------|
| `linalg.solve(a, b)` | Solve a linear matrix equation or system of linear scalar equations. |
| `linalg.tensorsolve(a, b[, axes])` | Solve the tensor equation `a x = b` for `x`. |
| `linalg.lstsq(a, b[, rcond])` | Return the least-squares solution to a linear matrix equation. |
| `linalg.inv(a)` | Compute the inverse of a matrix. |
| `linalg.pinv(a[, rcond, hermitian, rtol])` | Compute the (Moore-Penrose) pseudo-inverse of a matrix. |
| `linalg.tensorinv(a[, ind])` | Compute the 'inverse' of an N-dimensional array. |


#### Code Implementations

In [95]:

# 1. Solving a linear system using `linalg.solve(a, b)`
# Solve the system: Ax = b
A = np.array([[3, 1], [1, 2]])  # Coefficient matrix
b = np.array([9, 8])  # Right-hand side
x = np.linalg.solve(A, b)
print("Solution to Ax = b using linalg.solve:\n", x)

# 2. Solving a tensor equation using `linalg.tensorsolve(a, b)`
# Solve the tensor equation a x = b for x
a = np.array([[4, 5], [7, 8]])
b = np.array([1, 2])
tensor_solution = np.linalg.tensorsolve(a, b)
print("\nSolution to tensor equation a x = b using linalg.tensorsolve:\n", tensor_solution)

# 3. Finding least-squares solution using `linalg.lstsq(a, b)`
# Return the least-squares solution to a linear matrix equation
A_ls = np.array([[1, 1], [1, 2], [1, 3]])
b_ls = np.array([1, 2, 2])
x_ls, residuals, rank, s = np.linalg.lstsq(A_ls, b_ls, rcond=None)
print("\nLeast-squares solution to Ax = b using linalg.lstsq:\n", x_ls)

# 4. Computing the inverse of a matrix using `linalg.inv(a)`
A_inv = np.array([[1, 2], [3, 4]])
inverse_A = np.linalg.inv(A_inv)
print("\nInverse of matrix A using linalg.inv:\n", inverse_A)

# 5. Computing the pseudo-inverse of a matrix using `linalg.pinv(a)`
A_pinv = np.array([[1, 2], [3, 4], [5, 6]])
pseudo_inverse_A = np.linalg.pinv(A_pinv)
print("\nPseudo-inverse of matrix A using linalg.pinv:\n", pseudo_inverse_A)

# 6. Inverse of an N-dimensional array using `linalg.tensorinv(a)`
A_tensor = np.eye(4).reshape((2, 2, 2, 2))  # Create a 4D identity matrix
tensor_inverse_A = np.linalg.tensorinv(A_tensor)
print("\nInverse of an N-dimensional array using linalg.tensorinv:\n", tensor_inverse_A)


Solution to Ax = b using linalg.solve:
 [2. 3.]

Solution to tensor equation a x = b using linalg.tensorsolve:
 [ 0.66666667 -0.33333333]

Least-squares solution to Ax = b using linalg.lstsq:
 [0.66666667 0.5       ]

Inverse of matrix A using linalg.inv:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Pseudo-inverse of matrix A using linalg.pinv:
 [[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]

Inverse of an N-dimensional array using linalg.tensorinv:
 [[[[1. 0.]
   [0. 0.]]

  [[0. 1.]
   [0. 0.]]]


 [[[0. 0.]
   [1. 0.]]

  [[0. 0.]
   [0. 1.]]]]



### Other Matrix Operations

| Function | Description |
|----------|-------------|
| `diagonal(a[, offset, axis1, axis2])` | Return specified diagonals. |
| `linalg.diagonal(x[, offset])` | Returns specified diagonals of a matrix. |
| `linalg.matrix_transpose(x)` | Transposes a matrix (or a stack of matrices). |


#### Code Implementations

In [99]:
# 1. Extracting the diagonal of a matrix using `diagonal(a)`
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
diag = np.diagonal(A)
print("Diagonal of matrix A:\n", diag)

# 2. Extracting diagonals with offset using `diagonal(a, offset)`
# Offset = 1 means the diagonal above the main diagonal, -1 is below.
diag_offset = np.diagonal(A, offset=1)
print("\nDiagonal of matrix A with offset=1:\n", diag_offset)

# 4. Transposing a matrix using `linalg.matrix_transpose(x)`
# `matrix_transpose()` works on a matrix or a stack of matrices.
transpose_A = A.T
print("\nTranspose of matrix A using linalg.matrix_transpose:\n", transpose_A)

# Transposing a stack of matrices (3D array example)
B = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # Stack of two 2x2 matrices
transpose_B = np.transpose(B)
print("\nTranspose of stack of matrices B:\n", transpose_B)


Diagonal of matrix A:
 [1 5 9]

Diagonal of matrix A with offset=1:
 [2 6]

Transpose of matrix A using linalg.matrix_transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

Transpose of stack of matrices B:
 [[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]


### Exceptions

| Function | Description |
|----------|-------------|
| `linalg.LinAlgError` | Generic Python-exception-derived object raised by linalg functions. |

In [63]:
a=np.random.random((1,2))
a

array([[0.29371405, 0.63097612]])

In [62]:
c=np.linalg.eig(a)

LinAlgError: Last 2 dimensions of the array must be square

### Linear algebra on several matrices at once

This means that if for instance given an input array a.shape == (N, M, M), it is interpreted as a “stack” of N matrices, each of size M-by-M. . Similar specification applies to return values, for instance the determinant has det : (...) and will in this case return an array of shape det(a).shape == (N,)

## numpy.polynomial

A sub-package for efficiently dealing with polynomials.

Within the documentation for this sub-package, a “finite power series,” i.e., a polynomial (also referred to simply as a “series”) is represented by a 1-D numpy array of the polynomial’s coefficients, ordered from lowest order term to highest. For example, array([1,2,3]) represents P_0 + 2*P_1 + 3*P_2, where P_n is the n-th order basis polynomial applicable to the specific module in question.

| Function | Series Representation |
|---|---|
| Polynomial | Power series |
| Chebyshev | Chebyshev series |
| Legendre | Legendre series |
| Laguerre | Laguerre series |
| Hermite | Hermite series |
| HermiteE | HermiteE series |


polynomial.set_default_printstyle(style)

Set the default format for the string representation of polynomials.

Values for style must be valid inputs to __format__, i.e. ‘ascii’ or ‘unicode’.

## numpy.random

The numpy.random module implements pseudo-random number generators (PRNGs or RNGs, for short) with the ability to draw samples from a variety of probability distributions.

 In general, users will create a Generator instance with default_rng and call the various methods on it to obtain samples from different distributions.

In [102]:
rng = np.random.default_rng()
print(rng.random()) 
print(rng.standard_normal(10))
print(rng.integers(low=0, high=10, size=5))

0.25230112368401914
[-1.1014378  -0.49530431  1.60218554  0.61220116  0.30156135 -1.29965706
  0.37303369  0.14028498  1.25312827 -1.13902501]
[4 8 3 6 0]


In [105]:
import numpy as np
import secrets
import numpy as np
seed = secrets.randbits(128)  
rng1 = np.random.default_rng(seed)
print(rng1.random())
rng2 = np.random.default_rng(seed)
print(rng2.random())

0.6205109371795916
0.6205109371795916


Design of Generator

Users primarily interact with Generator instances. Each Generator instance owns a BitGenerator instance that implements the core RNG algorithm. The BitGenerator has a limited set of responsibilities. It manages state and provides functions to produce random doubles and random unsigned 32- and 64-bit values.

default_rng and BitGenerators delegate the conversion of seeds into RNG states to SeedSequence internally. SeedSequence implements a sophisticated algorithm that intermediates between the user’s input and the internal implementation details of each BitGenerator algorithm, each of which can require different amounts of bits for its state. 

> PCG-64 is a 128-bit implementation of O’Neill’s permutation congruential generator. PCG-64 has a period of  and supports advancing an arbitrary number of steps as well as streams. 

> References: 
> - “PCG, A Family of Better Random Number Generators”
> - O’Neill, Melissa E. “PCG: A Family of Simple Fast Space-Efficient Statistically Good Algorithms for Random Number Generation”

Parallel Generation

The included generators can be used in parallel, distributed applications in a number of ways:

- SeedSequence spawning

NumPy allows you to spawn new (with very high probability) independent BitGenerator and Generator instances via their spawn() method. This spawning is implemented by the SeedSequence used for initializing the bit generators random stream.

SeedSequence mixes sources of entropy in a reproducible way to set the initial state for independent and very probably non-overlapping BitGenerators.

SeedSequence implements an algorithm to process a user-provided seed, typically as an integer of some size, and to convert it into an initial state for a BitGenerator. It uses hashing techniques to ensure that low-quality seeds are turned into high quality initial states (at least, with very high probability).

- Sequence of integer seeds

As discussed in the previous section, SeedSequence can not only take an integer seed, it can also take an arbitrary-length sequence of (non-negative) integers. If one exercises a little care, one can use this feature to design ad hoc schemes for getting safe parallel PRNG streams with similar safety guarantees as spawning.

- Independent streams

Philox is a counter-based RNG based which generates values by encrypting an incrementing counter using weak cryptographic primitives. The seed determines the key that is used for the encryption. Unique keys create unique, independent streams. Philox lets you bypass the seeding algorithm to directly set the 128-bit key.

- Jumping the BitGenerator state

Users with a very large amount of parallelism will want to consult Upgrading PCG64 with PCG64DXSM.

In [ ]:
import secrets
from numpy.random import Philox

# 128-bit number as a seed
root_seed = secrets.getrandbits(128)
streams = [Philox(key=root_seed + stream_id) for stream_id in range(10)]

Concepts

- Random Generator
- Legacy Generator (RandomState)
- Bit generators
- Seeding and entropy
- Upgrading PCG64 with PCG64DXSM
- Compatibility policy

Features

- Parallel Applications
    - SeedSequence spawning
    - Sequence of integer seeds
    - Independent streams
    - Jumping the BitGenerator state
- Multithreaded Generation
- What’s new or different
- Comparing Performance
    - Recommendation
    - Timings
    - Performance on different operating systems
- C API for random
- Examples of using Numba, Cython, CFFI
    - Numba
    - Cython
    - CFFI
    - New BitGenerators
    - Examples

### Random Generator

The Generator provides access to a wide range of distributions, and served as a replacement for RandomState. The main difference between the two is that Generator relies on an additional BitGenerator to manage state and generate the random bits, which are then transformed into random values from useful distributions.

In [4]:
import numpy as np
rng = np.random.default_rng(12345)
print(rng)
rfloat = rng.random()
print(rfloat)
type(rfloat)

Generator(PCG64)
0.22733602246716966


float

In [5]:
import numpy as np
rng = np.random.default_rng(12345)
rints = rng.integers(low=0, high=10, size=3)
print(rints)
type(rints[0])

[6 2 7]


numpy.int64

In [6]:
import numpy as np
rng = np.random.default_rng(seed=42)
print(rng)
arr1 = rng.random((3, 3))
arr1

Generator(PCG64)


array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235],
       [0.7611397 , 0.78606431, 0.12811363]])

In [7]:
from numpy.random import Generator, PCG64
rng = Generator(PCG64())
rng.standard_normal()

1.4331746600464776

In [9]:
rng.bit_generator

In [10]:
child_generators = rng.spawn(4)
child_generators

[Generator(PCG64) at 0x11EAB8C80,
 Generator(PCG64) at 0x11EAB90E0,
 Generator(PCG64) at 0x11EAB8E40,
 Generator(PCG64) at 0x11EAB9700]

In [14]:
print(rng.integers(-10,10,size=(3,3)))
print(rng.random((3,2)))# Return random floats in the half-open interval [0.0, 1.0)

[[  1   3   4]
 [ -1  -6 -10]
 [ -2   1   9]]
[[0.74805007 0.09343495]
 [0.62319753 0.25423268]
 [0.07660544 0.60568201]]


numpy.random.Generator.choice

Generates a random sample from a given array

In [19]:

rng.choice(5, 3, p=[0.1, 0, 0.3, 0.6, 0])# With replacement
rng.choice(5, 3, replace=False)# Without replacement


array([2, 0, 3])

In [23]:
print(rng.choice([[0, 1, 2], [3, 4, 5], [6, 7, 8]], 2, replace=False))
print(rng.choice([[0, 1, 2], [3, 4, 5], [6, 7, 8]], 2, axis=1))

[[6 7 8]
 [0 1 2]]
[[0 0]
 [3 3]
 [6 6]]


In [24]:
rng = np.random.default_rng()
rng.bytes(10) # Return random bytes.

b'\xcb\x10$@\x0f\x8e@ \xd94'

numpy.random.shuffle

In [29]:
arr = np.arange(9).reshape((3, 3))
print(arr)
rng.shuffle(arr)
arr

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [0, 1, 2],
       [3, 4, 5]])

In [31]:
rng.shuffle(arr,axis=1)
arr

array([[8, 7, 6],
       [2, 1, 0],
       [5, 4, 3]])

numpy.random.Generator.permutation

Randomly permute a sequence, or return a permuted range.

In [32]:
rng.permutation([1, 4, 9, 12, 15])

array([ 1,  4, 15, 12,  9])

numpy.random.Generator.permuted

Randomly permute `x` along axis `axis`.

Unlike shuffle, each slice along the given axis is shuffled independently of the others.

In [44]:
x = np.arange(24).reshape(3, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [43]:
rng.shuffle(x, axis=1)
x

array([[ 0,  1,  7,  5,  6,  4,  2,  3],
       [ 8,  9, 15, 13, 14, 12, 10, 11],
       [16, 17, 23, 21, 22, 20, 18, 19]])

In [45]:
y = rng.permuted(x, axis=1, out=x)
x

array([[ 6,  7,  4,  3,  0,  1,  2,  5],
       [12, 13,  8, 14, 11, 15, 10,  9],
       [22, 17, 23, 19, 21, 16, 18, 20]])

The main difference between Generator.shuffle and Generator.permutation is that Generator.shuffle operates in-place, while Generator.permutation returns a copy.

By default, Generator.permuted returns a copy. To operate in-place with Generator.permuted, pass the same array as the first argument and as the value of the out parameter. 

Distributions

https://numpy.org/doc/stable/reference/random/generator.html#distributions

We can cover more on this later on, but this basically states that random provides generation of several types of distributions.

### Legacy Random Generation

The RandomState provides access to legacy generators. This generator is considered frozen and will have no further improvements. It is guaranteed to produce the same values as the final point release of NumPy v1.16. These all depend on Box-Muller normals or inverse CDF exponentials or gammas. This class should only be used if it is essential to have randoms that are identical to what would have been produced by previous versions of NumPy.

In [47]:
from numpy.random import MT19937
from numpy.random import RandomState

rs = RandomState(12345)
mt19937 = MT19937()
mt19937.state = rs.get_state()
rs2 = RandomState(mt19937)

# Same output
print(rs.standard_normal())
print(rs2.standard_normal())
print()
print(rs.random())
print(rs2.random())
print()
print(rs.standard_exponential())
print(rs2.standard_exponential())

-0.20470765948471295
-0.20470765948471295

0.18391881167709445
0.18391881167709445

0.22886020849774785
0.22886020849774785


### Multithreaded Generation

The four core distributions (random, standard_normal, standard_exponential, and standard_gamma) all allow existing arrays to be filled using the out keyword argument. Existing arrays need to be contiguous and well-behaved (writable and aligned).

In [48]:
from numpy.random import default_rng, SeedSequence
import multiprocessing
import concurrent.futures
import numpy as np

class MultithreadedRNG:
    def __init__(self, n, seed=None, threads=None):
        if threads is None:
            threads = multiprocessing.cpu_count()
        self.threads = threads

        seq = SeedSequence(seed)
        self._random_generators = [default_rng(s)
                                   for s in seq.spawn(threads)]

        self.n = n
        self.executor = concurrent.futures.ThreadPoolExecutor(threads)
        self.values = np.empty(n)
        self.step = np.ceil(n / threads).astype(np.int_)

    def fill(self):
        def _fill(random_state, out, first, last):
            random_state.standard_normal(out=out[first:last])

        futures = {}
        for i in range(self.threads):
            args = (_fill,
                    self._random_generators[i],
                    self.values,
                    i * self.step,
                    (i + 1) * self.step)
            futures[self.executor.submit(*args)] = i
        concurrent.futures.wait(futures)

    def __del__(self):
        self.executor.shutdown(False)

In [49]:
mrng = MultithreadedRNG(10000000, seed=12345)
print(mrng.values[-1])

mrng.fill()
print(mrng.values[-1])

0.0
-0.10623651713382791


In [51]:
print(mrng.threads)
%timeit mrng.fill()

10
8.93 ms ± 1.07 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


## numpy.strings

The numpy.strings module provides a set of universal functions operating on arrays of type numpy.str_ or numpy.bytes_. 

In [9]:
import numpy as np

# Create a sample array of strings
arr = np.array(['hello', 'WORLD', 'NumPy', 'sTRINGs', '12345'])

# String Operations
print("Add:", np.char.add(arr, ' suffix'))
print("Center:", np.char.center(arr, 10, fillchar='-'))
print("Capitalize:", np.char.capitalize(arr))
print("Lowercase:", np.char.lower(arr))
print("Uppercase:", np.char.upper(arr))
print("Strip:", np.char.strip(np.array([' hello ', ' world '])))
print("Replace:", np.char.replace(arr, 'l', 'L'))
print("Multiply:", np.char.multiply(arr, 3))

# Comparison Functions
print("Equal:", np.char.equal(arr, 'hello'))
print("Not Equal:", np.char.not_equal(arr, 'hello'))
print("Greater Than:", np.char.greater(arr, 'hello'))
print("Less Than:", np.char.less(arr, 'hello'))

# String Information Functions
print("Count 'l':", np.char.count(arr, 'l'))
print("Endswith 'y':", np.char.endswith(arr, 'y'))
print("Find 'o':", np.char.find(arr, 'o'))
print("IsAlpha:", np.char.isalpha(arr))
print("IsDigit:", np.char.isdigit(arr))
print("IsLower:", np.char.islower(arr))
print("IsUpper:", np.char.isupper(arr))
print("StartsWith 'h':", np.char.startswith(arr, 'h'))
print("String Lengths:", np.char.str_len(arr))

# Splitting and Joining
print("Split:", np.char.split(np.array('hello world numpy'), ' '))
print("Join:", np.char.join('-', arr))

# Encoding and Decoding
encoded = np.char.encode(arr, 'utf-8')
print("Encoded:", encoded)
print("Decoded:", np.char.decode(encoded, 'utf-8'))

# Formatting
print("ZFill:", np.char.zfill(np.array(['1', '12', '123']), 5))
# print("Format:", np.char.mod('%s is %d', np.array(['NumPy', 2023])))

# Title and Swapcase
print("Title:", np.char.title(arr))
print("Swapcase:", np.char.swapcase(arr))

Add: ['hello suffix' 'WORLD suffix' 'NumPy suffix' 'sTRINGs suffix'
 '12345 suffix']
Center: ['--hello---' '--WORLD---' '--NumPy---' '-sTRINGs--' '--12345---']
Capitalize: ['Hello' 'World' 'Numpy' 'Strings' '12345']
Lowercase: ['hello' 'world' 'numpy' 'strings' '12345']
Uppercase: ['HELLO' 'WORLD' 'NUMPY' 'STRINGS' '12345']
Strip: ['hello' 'world']
Replace: ['heLLo' 'WORLD' 'NumPy' 'sTRINGs' '12345']
Multiply: ['hellohellohello' 'WORLDWORLDWORLD' 'NumPyNumPyNumPy'
 'sTRINGssTRINGssTRINGs' '123451234512345']
Equal: [ True False False False False]
Not Equal: [False  True  True  True  True]
Greater Than: [False False False  True False]
Less Than: [False  True  True False  True]
Count 'l': [2 0 0 0 0]
Endswith 'y': [False False  True False False]
Find 'o': [ 4 -1 -1 -1 -1]
IsAlpha: [ True  True  True  True False]
IsDigit: [False False False False  True]
IsLower: [ True False False False False]
IsUpper: [False  True False False False]
StartsWith 'h': [ True False False False False]
String L

## numpy.testing

Common test support for all numpy test scripts.

This single module should provide all the common functionality for numpy tests in a single location, so that test scripts can just import it and work right away. 

The NumPy testing module provides a comprehensive set of tools for testing NumPy code and ensuring its correctness. Here's an overview of the main functions and features:

### Asserts

The testing module offers several assert functions for comparing arrays and values:

- `assert_allclose`: Checks if two objects are equal within a desired tolerance[1].
- `assert_array_almost_equal_nulp`: Compares two arrays relative to their spacing[1].
- `assert_array_max_ulp`: Verifies that array items differ by at most N Units in the Last Place[1].
- `assert_array_equal`: Checks if two array-like objects are exactly equal[1].
- `assert_array_less`: Ensures one array is element-wise less than another[1].
- `assert_equal`: Checks if two objects are equal[1].

### Exception and Warning Asserts

- `assert_raises`: Verifies that a specific exception is raised[1].
- `assert_raises_regex`: Checks for an exception with a matching error message[1].
- `assert_warns`: Ensures a specific warning is issued[1].
- `assert_no_warnings`: Verifies that no warnings are produced[1].
- `assert_no_gc_cycles`: Checks that no reference cycles are created[1].

### String Comparison

- `assert_string_equal`: Tests if two strings are identical[1].

### Decorators

- `decorate_methods`: Applies a decorator to all methods in a class matching a regular expression[1].

### Test Running

- `clear_and_catch_warnings`: Context manager for resetting warning registry[1].
- `measure`: Times the execution of a code snippet[1].
- `rundocs`: Runs doctests found in a given file[1].
- `suppress_warnings`: Context manager for suppressing specific warnings[1].

### Testing Custom Array Containers

For testing custom array implementations that use `__array_ufunc__` or `__array_function__`:

- `allows_array_ufunc`: Determines if a NumPy function can be overridden via `__array_ufunc__`[1].
- `allows_array_function`: Checks if a function can be overridden via `__array_function__`[1].
- `get_overridable_numpy_ufuncs`: Lists all NumPy ufuncs overridable via `__array_ufunc__`[1].
- `get_overridable_numpy_functions`: Lists all NumPy functions overridable via `__array_function__`[1].

These tools provide a robust framework for writing and running tests on NumPy code, ensuring that array operations, custom implementations, and various edge cases are correctly handled.

Citations:
[1] https://numpy.org/doc/stable/reference/routines.testing.html

In [10]:
import numpy as np
from numpy.testing import (
    assert_allclose, assert_array_equal, assert_array_less,
    assert_equal, assert_raises, assert_warns, assert_no_warnings,
    assert_string_equal, suppress_warnings
)

# Sample data for testing
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
c = np.array([1.000001, 2.000002, 3.000003])
d = np.array([0, 1, 2])

# Basic assert functions
assert_array_equal(a, b)
assert_allclose(a, c, rtol=1e-5)
assert_array_less(d, a)

# Equality checks
assert_equal(a[0], b[0])
assert_string_equal("numpy", "numpy")

# Exception testing
def raise_value_error():
    raise ValueError("Test error")

assert_raises(ValueError, raise_value_error)

# Warning testing
def warn_user():
    import warnings
    warnings.warn("This is a test warning", UserWarning)

assert_warns(UserWarning, warn_user)

# No warnings
with assert_no_warnings():
    x = np.sum([1, 2, 3])

# Suppress specific warnings
with suppress_warnings() as sup:
    sup.filter(UserWarning)
    warn_user()  # This warning will be suppressed

# Custom tests
def test_array_creation():
    x = np.array([1, 2, 3])
    assert_array_equal(x, np.array([1, 2, 3]))

def test_array_operations():
    x = np.array([1, 2, 3])
    y = np.array([4, 5, 6])
    assert_array_equal(x + y, np.array([5, 7, 9]))

# Run tests
if __name__ == "__main__":
    test_array_creation()
    test_array_operations()
    print("All tests passed!")

All tests passed!


## numpy.typing