# Documentation Tour - NumPy

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

- [Beginner's Guide](https://numpy.org/doc/stable/user/absolute_beginners.html)
- [User Guide](https://numpy.org/doc/stable/user/index.html#user)
- [API Reference](https://numpy.org/doc/stable/reference/index.html#reference)
- [Contributor's Guide](https://numpy.org/doc/stable/dev/index.html#devindex)

In [ ]:
%pip install numpy

If you get errors NOT related to installing of Numpy, you probably need not worry about that issue. Our main goal for now is to use NumPy properly and to its fullest extent. 

In [1]:
import numpy as np
print("Numpy Version is: ",np.__version__)

Numpy Version is:  1.26.4


# NumPy Reference

## NumPy Module Structure

Regular Namespaces


> A namespace is a collection of well-defined symbolic names along with information about the object that each name references. (Basically like a dictionary). 

> This is good when you are defining submodules too, they make things for interpreters to identify the specific submodule of a module to be loaded.

- numpy
- numpy.exceptions
- numpy.fft
- numpy.linalg
- numpy.polynomial
- numpy.random
- numpy.strings
- numpy.testing
- numpy.typing

Special purpose Namespaces

- numpy.ctypeslib - interacting with NumPy objects with ctypes 
- numpy.dtypes - dtype classes - (typically not used directly by end - users)
- numpy.emath - mathematical functions - with automatic domain
- numpy.lib - utilities & functionality - which do not fit the main namespace
- numpy.rec - record arrays (largely superseded by dataframe libraries)
- numpy.version - small module with more detailed version info

## numpy.exceptions

General exceptions used by Numpy. Note that some exceptions may be module specific, such as linear algebra errors.

>Only available from NumPy version 1.25

In [2]:
np.exceptions

<module 'numpy.exceptions' from '/Users/smatcha/anaconda3/lib/python3.11/site-packages/numpy/exceptions.py'>

Warnings

- ComplexWarning: The warning raised when casting a complex dtype to a real dtype.
- Visible Depreciation Warning: Visible deprecation warning.
- RankWarning: Warning related to Matrix Warning Issues

Exceptions

- AxisError: Axis Supplied was Invalid.
- DTypePromotionError: Multiple DTypes could not be converted to a common one. Comes from a form of `TypeError`.
- TooHardError: max_work was exceeded.

In [7]:
print(np.exceptions.ComplexWarning)
print(np.exceptions.VisibleDeprecationWarning)
print(np.exceptions.RankWarning)
print(np.exceptions.AxisError)
print(np.exceptions.DTypePromotionError)
print(np.exceptions.TooHardError)

<class 'numpy.exceptions.ComplexWarning'>
<class 'numpy.exceptions.VisibleDeprecationWarning'>
<class 'numpy.exceptions.RankWarning'>
<class 'numpy.exceptions.AxisError'>
<class 'numpy.exceptions.DTypePromotionError'>
<class 'numpy.exceptions.TooHardError'>


In [17]:
array = np.array([(1,2),(3,4)])
print(array.shape)

#Axis Error Demostration
_sum = np.sum(array,axis=0)
print(_sum)
_sum = np.sum(array,axis=1)
print(_sum)
_sum = np.sum(array,axis=2) # No Axis --> Should give Axis error
print(_sum)

(2, 2)
[4 6]
[3 7]


AxisError: axis 2 is out of bounds for array of dimension 2

In [18]:
np.result_type(np.dtype("M8[s]"), np.complex128)

DTypePromotionError: The DType <class 'numpy.dtypes.DateTime64DType'> could not be promoted by <class 'numpy.dtypes.Complex128DType'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtypes.DateTime64DType'>, <class 'numpy.dtypes.Complex128DType'>)

In [20]:
dtype1 = np.dtype([("field1", np.float64), ("field2", np.int64)])
dtype2 = np.dtype([("field1", np.float64)])
np.promote_types(dtype1, dtype2)  

DTypePromotionError: field names `('field1', 'field2')` and `('field1',)` mismatch.

In [5]:
import numpy as np

def complex_numpy_function(data):
    # Imagine this operation is too complex or the array is too large
    if data.size > 10**6:
        raise np.exceptions.TooHardError("This operation is too hard for the current dataset size!")
    
    # A simple operation that won't raise an error for small datasets
    return np.mean(data)

# Example usage
data = np.random.rand(10**7)  # A large dataset
result = complex_numpy_function(data)
print("Mean of data:", result)


TooHardError: This operation is too hard for the current dataset size!

## numpy.fft

Numpy Module for [Fourier Transforms](https://en.wikipedia.org/wiki/Fourier_transform).

## numpy.linalg

The NumPy linear algebra functions rely on [BLAS](https://en.wikipedia.org/wiki/Basic_Linear_Algebra_Subprograms) and [LAPACK](https://en.wikipedia.org/wiki/LAPACK) to provide efficient low level implementations of standard linear algebra algorithms. 


> Basic Linear Algebra Subprograms (BLAS) is a specification that prescribes a set of low-level routines for performing common linear algebra operations such as vector addition, scalar multiplication, dot products, linear combinations, and matrix multiplication. They are the de facto standard low-level routines for linear algebra libraries; the routines have bindings for both C ("CBLAS interface") and Fortran ("BLAS interface"). Although the BLAS specification is general, BLAS implementations are often optimized for speed on a particular machine, so using them can bring substantial performance benefits. BLAS implementations will take advantage of special floating point hardware such as vector registers or SIMD instructions.

> LAPACK ("Linear Algebra Package") is a standard software library for numerical linear algebra. It provides routines for solving systems of linear equations and linear least squares, eigenvalue problems, and singular value decomposition. It also includes routines to implement the associated matrix factorizations such as LU, QR, Cholesky and Schur decomposition. LAPACK was originally written in FORTRAN 77, but moved to Fortran 90 in version 3.2 (2008).[3] The routines handle both real and complex matrices in both single and double precision. LAPACK relies on an underlying BLAS implementation to provide efficient and portable computational building blocks for its routines.


References:

- Anderson, E.; Bai, Z.; Bischof, C.; Blackford, S.; Demmel, J.; Dongarra, J.; Du Croz, J.; Greenbaum, A.; Hammarling, S.; McKenney, A.; Sorensen, D. (1999). LAPACK Users' Guide (Third ed.). Philadelphia, PA: Society for Industrial and Applied Mathematics. ISBN 0-89871-447-8. Retrieved 28 May 2022.

- "LAPACK 3.2 Release Notes". 16 November 2008.


Those libraries may be provided by NumPy itself using C versions of a subset of their reference implementations but, when possible, highly optimized libraries that take advantage of specialized processor functionality are preferred. Examples of such libraries are [OpenBLAS](https://www.openblas.net), [MKL (TM)](https://en.wikipedia.org/wiki/Math_Kernel_Library), and [ATLAS](https://math-atlas.sourceforge.net). Because those libraries are multithreaded and processor dependent, environmental variables and external packages such as **threadpoolctl** may be needed to control the number of threads or specify the processor architecture.

The SciPy library also contains a `linalg` submodule, and there is overlap in the functionality provided by the SciPy and NumPy submodules. SciPy contains functions not found in numpy.linalg, such as functions related to [LU decomposition](https://en.wikipedia.org/wiki/LU_decomposition) and the [Schur decomposition](https://en.wikipedia.org/wiki/Schur_decomposition), multiple ways of calculating the pseudoinverse, and matrix transcendentals such as the matrix logarithm.

> Axes in NumPy Arrays

- Axis 0: This is the first axis of a NumPy array. It typically represents the rows in a 2D array (or the outermost dimension in higher-dimensional arrays). When you perform operations along axis 0, you are usually aggregating or processing across all rows.

- Axis 1: This is the second axis of a NumPy array. In a 2D array, it corresponds to the columns. When you perform operations along axis 1, you are aggregating or processing across all columns.

> The `@` operator is used for matrix multiplication between two matrices. `np.matmul` 

In [3]:
A = np.matrix([[2,4,5],[5,4,2],[3,1,6]])
B = np.matrix([[1,1,1],[5,3,7],[10,8,9]])
A,B

(matrix([[2, 4, 5],
         [5, 4, 2],
         [3, 1, 6]]),
 matrix([[ 1,  1,  1],
         [ 5,  3,  7],
         [10,  8,  9]]))

In [4]:
C = np.matmul(A,B)
print(C)
D = A@B
print(D)

[[72 54 75]
 [45 33 51]
 [68 54 64]]
[[72 54 75]
 [45 33 51]
 [68 54 64]]


### Matrix and vector products

| Function | Description |
|---|---|
| `dot(a, b[, out])` | Dot product of two arrays. |
| `linalg.multi_dot(arrays, *[, out])` | Compute the dot product of two or more arrays in a single function call, while automatically selecting the fastest evaluation order. |
| `vdot(a, b, /)` | Return the dot product of two vectors. |
| `vecdot(x1, x2, /[, out, casting, order, ...])` | Vector dot product of two arrays. |
| `linalg.vecdot(x1, x2, /, *[, axis])` | Computes the vector dot product. |
| `inner(a, b, /)` | Inner product of two arrays. |
| `outer(a, b[, out])` | Compute the outer product of two vectors. |
| `matmul(x1, x2, /[, out, casting, order, ...])` | Matrix product of two arrays. |
| `linalg.matmul(x1, x2, /)` | Computes the matrix product. |
| `tensordot(a, b[, axes])` | Compute tensor dot product along specified axes. |
| `linalg.tensordot(x1, x2, /, *[, axes])` | Compute tensor dot product along specified axes. |
| `einsum(subscripts, *operands[, out, dtype, ...])` | Evaluates the Einstein summation convention on the operands. |
| `einsum_path(subscripts, *operands[, optimize])` | Evaluates the lowest cost contraction order for an einsum expression by considering the creation of intermediate arrays. |
| `linalg.matrix_power(a, n)` | Raise a square matrix to the (integer) power n. |
| `kron(a, b)` | Kronecker product of two arrays. |
| `linalg.cross(x1, x2, /, *[, axis])` | Returns the cross product of 3-element vectors. |


#### Code Implementations

dot and multi_dot

In [21]:
a = np.matrix([[1, 0], [0, 1]])
b = np.matrix([[4, 1], [2, 2]])
a,b

(matrix([[1, 0],
         [0, 1]]),
 matrix([[4, 1],
         [2, 2]]))

In [22]:
np.dot(a, b)

matrix([[4, 1],
        [2, 2]])

In [16]:
from numpy.linalg import multi_dot
# Prepare some data
A = np.random.random((10000, 100))
B = np.random.random((100, 1000))
C = np.random.random((1000, 5))
D = np.random.random((5, 333))
# the actual dot multiplication
_ = multi_dot([A, B, C, D])
print(_.shape)
print(_)
_ = np.dot(np.dot(np.dot(A, B), C), D)
print(_.shape)
print(_)

(10000, 333)
[[31229.38409299 20939.90203527 40629.31284565 ... 30962.7328555
  15130.13869885 33696.14496461]
 [32460.15657146 21776.22504512 42222.79740772 ... 32181.91117219
  15717.12060996 35021.8272593 ]
 [33975.56956356 22783.2654148  44192.31254239 ... 33685.23677008
  16456.44989155 36653.8879767 ]
 ...
 [30819.00179991 20662.86000021 40085.70237776 ... 30557.55636294
  14928.63179029 33249.71888371]
 [31231.65505436 20946.6866803  40622.76184163 ... 30964.76317615
  15122.85907141 33692.71657728]
 [30386.01828732 20388.72955968 39530.60588209 ... 30124.40762162
  14713.88266383 32788.19320877]]
(10000, 333)
[[31229.38409299 20939.90203527 40629.31284565 ... 30962.7328555
  15130.13869885 33696.14496461]
 [32460.15657146 21776.22504512 42222.79740772 ... 32181.91117219
  15717.12060996 35021.8272593 ]
 [33975.56956356 22783.2654148  44192.31254239 ... 33685.23677008
  16456.44989155 36653.8879767 ]
 ...
 [30819.00179991 20662.86000021 40085.70237776 ... 30557.55636294
  14928.

vdot

In [23]:
a = np.array([[1, 4], [5, 6]])
b = np.array([[4, 1], [2, 2]])
a,b

(array([[1, 4],
        [5, 6]]),
 array([[4, 1],
        [2, 2]]))

Note that vdot handles multidimensional arrays differently than dot: **it does not perform a matrix product, but flattens input arguments to 1-D vectors first**. Consequently, it should only be used for vectors.

In [24]:
np.vdot(a, b)
np.vdot(b, a)

30

Inner Product

Ordinary inner product of vectors for 1-D arrays (without complex conjugation), **in higher dimensions a sum product over the last axes.**

In [25]:
a = np.arange(24).reshape((2,3,4))
b = np.arange(4)
a,b

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([0, 1, 2, 3]))

In [27]:
c = np.inner(a, b)
print(c.shape)
c

(2, 3)


array([[ 14,  38,  62],
       [ 86, 110, 134]])

In [28]:
a = np.arange(2).reshape((1,1,2))
b = np.arange(6).reshape((3,2))
a,b

(array([[[0, 1]]]),
 array([[0, 1],
        [2, 3],
        [4, 5]]))

In [30]:
c = np.inner(a, b)
print(c.shape)
c

(1, 1, 3)


array([[[1, 3, 5]]])

Outer Product

In [33]:
d=1j*np.linspace(2, -2, 5)
print(d.shape)
im = np.outer(1j*np.linspace(2, -2, 5), np.ones((5,)))
im

(5,)


array([[0.+2.j, 0.+2.j, 0.+2.j, 0.+2.j, 0.+2.j],
       [0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.-1.j, 0.-1.j, 0.-1.j, 0.-1.j, 0.-1.j],
       [0.-2.j, 0.-2.j, 0.-2.j, 0.-2.j, 0.-2.j]])

In [31]:
x = np.array(['a', 'b', 'c'], dtype=object)
np.outer(x, [1, 2, 3])

array([['a', 'aa', 'aaa'],
       ['b', 'bb', 'bbb'],
       ['c', 'cc', 'ccc']], dtype=object)

Tensordot

In [39]:

# Define the arrays
A = np.array([[1, 2],
              [3, 4]])

B = np.array([5, 6])

# Compute the tensor dot product
result = np.tensordot(A, B, axes=1)
print(result)
result = np.tensordot(A, B, axes=0)
print(result)


[17 39]
[[[ 5  6]
  [10 12]]

 [[15 18]
  [20 24]]]


einsum

`numpy.einsum(subscripts, *operands, out=None, dtype=None, order='K', casting='safe', optimize=False)`

Evaluates the Einstein summation convention on the operands.

Using the Einstein summation convention, many common multi-dimensional, linear algebraic array operations can be represented in a simple fashion. In implicit mode einsum computes these values.

In explicit mode, einsum provides further flexibility to compute other array operations that might not be considered classical Einstein summation operations, by disabling, or forcing summation over specified subscript labels.

**Parameters:**

* **subscripts:str :** Specifies the subscripts for summation as a comma-separated list of subscript labels. An implicit (classical Einstein summation) calculation is performed unless the explicit indicator "->" is included as well as subscript labels of the precise output form.
* **operands:** A list of array-like objects that are the arrays for the operation.
* **out:** Optional ndarray. If provided, the calculation is done into this array.
* **dtype:** Optional data-type. If provided, forces the calculation to use the specified data type. Note that you may have to also give a more liberal `casting` parameter to allow the conversions. Default is None.
* **order:** Optional string specifying the memory layout of the output. "C" means it should be C contiguous, "F" means it should be Fortran contiguous, "A" means it should be "F" if the inputs are all "F", "C" otherwise, and "K" means it should be as close to the layout as the inputs as is possible, including arbitrarily permuted axes. Default is "K".
* **casting:** Optional string controlling what kind of data casting may occur. Setting this to "unsafe" is not recommended, as it can adversely affect accumulations.
    * "no": Data types should not be cast at all.
    * "equiv": Only byte-order changes are allowed.
    * "safe": Only casts which can preserve values are allowed.
    * "same_kind": Only safe casts or casts within a kind, like float64 to float32, are allowed.
    * "unsafe": Any data conversions may be done.
  Default is "safe".
* **optimize:** Optional boolean or string controlling whether intermediate optimization should occur. No optimization will occur if False, and True will default to the "greedy" algorithm. Also accepts an explicit contraction list from the `np.einsum_path` function. See `np.einsum_path` for more details. Defaults to False.

**Returns:**

* **output:** ndarray. The calculation based on the Einstein summation convention.

In [45]:
a = np.arange(25).reshape(5,5)
print(a)
print(np.einsum('ii', a))
print(np.einsum('ij->j', a))
print(np.sum(a,axis=0))#row-wise
print(np.einsum('ij->i', a))
print(np.sum(a,axis=1))#column-wise

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
60
[50 55 60 65 70]
[50 55 60 65 70]
[ 10  35  60  85 110]
[ 10  35  60  85 110]


In [47]:
c = np.arange(6).reshape(2,3)
print(c)
print("")
print(np.einsum('ji', c))
print(np.einsum('ij->ji', c))
print(np.einsum(c, [1,0]))
print(np.transpose(c))

[[0 1 2]
 [3 4 5]]

[[0 3]
 [1 4]
 [2 5]]
[[0 3]
 [1 4]
 [2 5]]
[[0 3]
 [1 4]
 [2 5]]
[[0 3]
 [1 4]
 [2 5]]


einsum_path

Evaluates the lowest cost contraction order for an einsum expression by considering the creation of intermediate arrays.

In [50]:
np.random.seed(123)
a = np.random.rand(2, 2)
b = np.random.rand(2, 5)
c = np.random.rand(5, 2)
path_info = np.einsum_path('ij,jk,kl->il', a, b, c, optimize='greedy')
print(path_info[0])
print(path_info[1])

['einsum_path', (1, 2), (0, 1)]
  Complete contraction:  ij,jk,kl->il
         Naive scaling:  4
     Optimized scaling:  3
      Naive FLOP count:  1.200e+02
  Optimized FLOP count:  5.700e+01
   Theoretical speedup:  2.105
  Largest intermediate:  4.000e+00 elements
--------------------------------------------------------------------------
scaling                  current                                remaining
--------------------------------------------------------------------------
   3                   kl,jk->jl                                ij,jl->il
   3                   jl,ij->il                                   il->il


In [51]:
d=a@b@c
print(d.shape)

(2, 2)


matrix_power

In [54]:
np.linalg.matrix_power(2*np.eye(3),5)

array([[32.,  0.,  0.],
       [ 0., 32.,  0.],
       [ 0.,  0., 32.]])

np.kron

Kronecker product of two arrays.

Computes the Kronecker product, a composite array made of blocks of the second array scaled by the first.

In [56]:
import numpy as np
print(np.kron([1,10,100], [5,6,7]))
print(np.kron([1,10,100], [5,6,7]).shape)


[  5   6   7  50  60  70 500 600 700]
(9,)


np.cross

In [58]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.cross(x, y)

array([-3,  6, -3])

### Decompositions

| Function | Description |
|----------|-------------|
| `linalg.cholesky(a, /, *[, upper])` | Cholesky decomposition. |
| `linalg.outer(x1, x2, /)` | Compute the outer product of two vectors. |
| `linalg.qr(a[, mode])` | Compute the QR factorization of a matrix. |
| `linalg.svd(a[, full_matrices, compute_uv, ...])` | Singular Value Decomposition (SVD). |
| `linalg.svdvals(x, /)` | Returns the singular values of a matrix (or a stack of matrices) `x`. |

#### Code Implementations

[Cholesky Decomposition](https://en.wikipedia.org/wiki/Cholesky_decomposition)

The Cholesky decomposition is a decomposition of a Hermitian, positive-definite matrix into the product of a lower triangular matrix and its conjugate transpose, which is useful for efficient numerical solutions, e.g., Monte Carlo simulations.

$${\displaystyle \mathbf {A} =\mathbf {LL} ^{*}}$$


In [65]:
A = np.array([[4, 12, -16],
              [12, 37, -52],
              [-16, -52, 89]])

# Perform Cholesky decomposition
L = np.linalg.cholesky(A)

print(L)
print(L@np.transpose(L))

[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8. -4.  3.]]
[[  4.  12. -16.]
 [ 12.  37. -52.]
 [-16. -52.  89.]]


QR Factorization

Compute the qr factorization of a matrix.

QR factorization is a matrix decomposition that expresses a matrix as the product of an orthogonal matrix and an upper triangular matrix. This decomposition is particularly useful in numerical linear algebra for solving linear least squares problems, computing eigenvalues, and performing matrix inversion.

In [66]:
# Create a matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Perform QR factorization
Q, R = np.linalg.qr(A)

print("Q:\n", Q)
print("R:\n", R)

Q:
 [[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
R:
 [[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -7.58790979e-16]]


[SVD](https://en.wikipedia.org/wiki/Singular_value_decomposition) 

The Singular Value Decomposition (SVD) is a powerful matrix factorization technique that decomposes a matrix into three matrices:

1. **U:** An orthogonal matrix of dimensions m x m.
2. **Σ:** A diagonal matrix of dimensions m x n with non-negative real numbers on the diagonal.
3. **V^:** The conjugate transpose of an orthogonal matrix V of dimensions n x n.

**Mathematical Representation:**

```
M = UΣV^
```

**Significance of SVD:**

* **Singular Values:** The diagonal elements of Σ are called singular values. They represent the "scale" or importance of each dimension in the matrix.
* **Principal Components:** The columns of U are called left singular vectors. They represent the principal components of the data in the matrix.
* **Orthogonal Basis:** The columns of V* are called right singular vectors. They form an orthogonal basis for the column space of the matrix.

**Applications of SVD:**

* **Data Analysis:**
    * **Dimensionality Reduction:** SVD can be used to reduce the dimensionality of data while preserving the most important information.
    * **Principal Component Analysis (PCA):** PCA is a direct application of SVD for dimensionality reduction.
    * **Latent Semantic Analysis (LSA):** LSA uses SVD to uncover the underlying semantic structure of a collection of documents.
* **Image Processing:**
    * **Image Compression:** SVD can be used to compress images by discarding small singular values.
    * **Image Denoising:** SVD can be used to remove noise from images.
* **Recommendation Systems:**
    * **Collaborative Filtering:** SVD can be used to predict user preferences in collaborative filtering systems.
* **Numerical Linear Algebra:**
    * **Solving Systems of Linear Equations:** SVD can be used to solve systems of linear equations, even when the matrix is singular or ill-conditioned.

`linalg.svd(a, full_matrices=True, compute_uv=True, hermitian=False)`

When a is a 2D array, and full_matrices=False, then it is factorized as u @ np.diag(s) @ vh = (u * s) @ vh, where u and the Hermitian transpose of vh are 2D arrays with orthonormal columns and s is a 1D array of a’s singular values. 

In [67]:
import numpy as np
rng = np.random.default_rng()
a = rng.normal(size=(9, 6)) + 1j*rng.normal(size=(9, 6))
b = rng.normal(size=(2, 7, 8, 3)) + 1j*rng.normal(size=(2, 7, 8, 3))

In [69]:
U, S, Vh = np.linalg.svd(a, full_matrices=True)
U.shape, S.shape, Vh.shape

((9, 9), (6,), (6, 6))

In [70]:
U, S, Vh

(array([[-0.02856343-0.28113663j, -0.16482704-0.16951731j,
          0.40571265-0.27143117j,  0.15562044-0.02691557j,
          0.0509328 +0.11873621j, -0.35885863-0.07700922j,
         -0.51614568-0.20868509j,  0.05315293+0.34890927j,
          0.08465851-0.08907453j],
        [ 0.25102205-0.30094391j,  0.11564509-0.0385054j ,
          0.00408794+0.34182338j, -0.18414345-0.01607789j,
         -0.03300943+0.08540237j, -0.00638603+0.54164339j,
          0.1680757 +0.01149509j,  0.17421381+0.43499778j,
         -0.17390448-0.31707664j],
        [ 0.07368374+0.19398869j, -0.00306821-0.04219004j,
         -0.43260047-0.15580114j,  0.20395769+0.21372929j,
          0.44639212-0.08982823j,  0.10847507-0.03484118j,
         -0.03232913-0.25980736j, -0.05430668+0.45599239j,
         -0.34181987+0.19968387j],
        [ 0.14941359-0.05592978j,  0.04681513-0.01157549j,
          0.19911661+0.05942054j,  0.36114919-0.00873065j,
         -0.23467614-0.05779046j, -0.09919902+0.26981064j,
         -

### Matrix Eigenvalues

| Function | Description |
|----------|-------------|
| `linalg.eig(a)` | Compute the eigenvalues and right eigenvectors of a square array. |
| `linalg.eigh(a[, UPLO])` | Return the eigenvalues and eigenvectors of a complex Hermitian (conjugate symmetric) or a real symmetric matrix. |
| `linalg.eigvals(a)` | Compute the eigenvalues of a general matrix. |
| `linalg.eigvalsh(a[, UPLO])` | Compute the eigenvalues of a complex Hermitian or real symmetric matrix. |

Eigen Decomposition (linalg.eig)

In linear algebra, eigendecomposition is the factorization of a matrix into a canonical form, whereby the matrix is represented in terms of its eigenvalues and eigenvectors. Only diagonalizable matrices can be factorized in this way. 

A (nonzero) vector v of dimension N is an eigenvector of a square N × N matrix A if it satisfies a linear equation of the form

$$\displaystyle \mathbf {A} \mathbf {v} =\lambda \mathbf {v}$$ 

In [72]:
import numpy as np
from numpy import linalg as LA

eigenvalues, eigenvectors = LA.eig(np.diag((1, 2, 3)))
eigenvalues, eigenvectors

(array([1., 2., 3.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [74]:
LA.eigvals(np.diag((1,2,3)))

array([1., 2., 3.])

Similar methods exist for hermitians. 


### Norms and Other Numbers

| Function | Description |
|----------|-------------|
| `linalg.norm(x[, ord, axis, keepdims])` | Matrix or vector norm. |
| `linalg.matrix_norm(x, /, *[, keepdims, ord])` | Computes the matrix norm of a matrix (or a stack of matrices). |
| `linalg.vector_norm(x, /, *[, axis, ...])` | Computes the vector norm of a vector (or batch of vectors). |
| `linalg.cond(x[, p])` | Compute the condition number of a matrix. |
| `linalg.det(a)` | Compute the determinant of an array. |
| `linalg.matrix_rank(A[, tol, hermitian, rtol])` | Return the matrix rank using the SVD method. |
| `linalg.slogdet(a)` | Compute the sign and logarithm of the determinant of an array. |
| `trace(a[, offset, axis1, axis2, dtype, out])` | Return the sum along diagonals of the array. |
| `linalg.trace(x[, offset, dtype])` | Returns the sum along specified diagonals of a matrix. |


#### Code Implementations


### Solving Equations and Inverting Matrices

| Function | Description |
|----------|-------------|
| `linalg.solve(a, b)` | Solve a linear matrix equation or system of linear scalar equations. |
| `linalg.tensorsolve(a, b[, axes])` | Solve the tensor equation `a x = b` for `x`. |
| `linalg.lstsq(a, b[, rcond])` | Return the least-squares solution to a linear matrix equation. |
| `linalg.inv(a)` | Compute the inverse of a matrix. |
| `linalg.pinv(a[, rcond, hermitian, rtol])` | Compute the (Moore-Penrose) pseudo-inverse of a matrix. |
| `linalg.tensorinv(a[, ind])` | Compute the 'inverse' of an N-dimensional array. |


#### Code Implementations


### Other Matrix Operations

| Function | Description |
|----------|-------------|
| `diagonal(a[, offset, axis1, axis2])` | Return specified diagonals. |
| `linalg.diagonal(x[, offset])` | Returns specified diagonals of a matrix. |
| `linalg.matrix_transpose(x)` | Transposes a matrix (or a stack of matrices). |


### Exceptions

| Function | Description |
|----------|-------------|
| `linalg.LinAlgError` | Generic Python-exception-derived object raised by linalg functions. |

In [63]:
a=np.random.random((1,2))
a

array([[0.29371405, 0.63097612]])

In [62]:
c=np.linalg.eig(a)

LinAlgError: Last 2 dimensions of the array must be square

### Linear algebra on several matrices at once

This means that if for instance given an input array a.shape == (N, M, M), it is interpreted as a “stack” of N matrices, each of size M-by-M. . Similar specification applies to return values, for instance the determinant has det : (...) and will in this case return an array of shape det(a).shape == (N,)

## numpy.polynomial

## numpy.random

## numpy.strings

## numpy.testing

## numpy.typing